// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

using JIM.Models.Core.DTOs;
using JIM.Models.Transactional;
using JIM.Models.Transactional.DTOs;
using JIM.Web.Models.Api;
using NUnit.Framework;

namespace JIM.Web.Api.Tests;

/// <summary>
/// The Pending Export detail REST DTO's "Value from" column (#399): <see cref="PendingExportDetailDto"/> carries
/// each Connected System attribute's value source, mapped from <see cref="PendingExportValueSource"/>.
/// </summary>
[TestFixture]
public class PendingExportValueSourceDtoTests
{
    [Test]
    public void FromModel_SingleAttributeSource_MapsSourceAttributeAndOrigin()
    {
        var model = new PendingExportValueSource
        {
            ConnectedSystemAttributeId = 42,
            SourceMetaverseAttributeId = 5,
            SourceMetaverseAttributeName = "mail",
            Origin = new ValueOrigin
            {
                Kind = ValueOriginKind.SynchronisationRule,
                ConnectedSystemId = 3,
                ConnectedSystemName = "HR",
                SyncRuleId = 9,
                SyncRuleName = "HR Import"
            },
            HasSeveralOrigins = false
        };

        var dto = PendingExportValueSourceDto.FromModel(model);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(dto.ConnectedSystemAttributeId, Is.EqualTo(42));
            Assert.That(dto.IsComputed, Is.False);
            Assert.That(dto.SourceMetaverseAttributeId, Is.EqualTo(5));
            Assert.That(dto.SourceMetaverseAttributeName, Is.EqualTo("mail"));
            Assert.That(dto.Origin, Is.Not.Null);
            Assert.That(dto.Origin!.ConnectedSystemName, Is.EqualTo("HR"));
            Assert.That(dto.HasSeveralOrigins, Is.False);
        }
    }

    [Test]
    public void FromModel_ComputedSource_OmitsOrigin()
    {
        var model = new PendingExportValueSource
        {
            ConnectedSystemAttributeId = 42,
            IsComputed = true,
            Expression = "mv[\"mail\"] ?? mv[\"upn\"]"
        };

        var dto = PendingExportValueSourceDto.FromModel(model);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(dto.IsComputed, Is.True);
            Assert.That(dto.Expression, Is.EqualTo("mv[\"mail\"] ?? mv[\"upn\"]"));
            Assert.That(dto.Origin, Is.Null);
            Assert.That(dto.SourceMetaverseAttributeId, Is.Null);
        }
    }

    [Test]
    public void FromDetailResult_ValueSourcesPresent_AreMappedOntoTheDetailDto()
    {
        var pendingExport = new PendingExport { Id = System.Guid.NewGuid(), ChangeType = PendingExportChangeType.Update };
        var result = new PendingExportDetailResult
        {
            PendingExport = pendingExport,
            ValueSources =
            {
                new PendingExportValueSource { ConnectedSystemAttributeId = 42, IsComputed = true, Expression = "Generated by JIM" }
            }
        };

        var dto = PendingExportDetailDto.FromDetailResult(result);

        Assert.That(dto.ValueSources, Has.Count.EqualTo(1));
        Assert.That(dto.ValueSources[0].ConnectedSystemAttributeId, Is.EqualTo(42));
    }
}
