services:

  adminer:
    container_name: JIM.Adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - jim.database

  jim.database:
    container_name: JIM.Database
    image: postgres:18
    restart: always
    volumes:
      - jim-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=jim
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jim
    ports:
      - "5432:5432"

volumes:
  jim-db-volume:
    name: jim-db-volume