# Copyright (c) Tetron Limited. All rights reserved.
# Licensed under the Tetron Commercial License. See LICENSE file in the project root.

<#
.SYNOPSIS
    Test Scenario 026: Metaverse-Derived Attribute Flows

.DESCRIPTION
    Exercises Metaverse-Derived Attribute Flows (#1750): import Attribute Flows whose expressions read
    mv["..."], evaluated by JIM in dependency order within one synchronisation, and re-evaluated by
    the hosting system's next synchronisation when an input changes in another system (the derived-input
    mark).

    The substrate is Scenario 001's, composed by Setup-Scenario-026.ps1 (Setup-Scenario-001.ps1
    -GenerateAccountName -DeriveFromAccountName), with the HR CSV generated by Get-OrGenerate-TestCSV.ps1
    -OmitItOwnedAttributes so the HR feed carries no samAccountName, email or userPrincipalName:

      Account Name         generated, Lower(firstName).Lower(lastName), OnlyIfTaken   step 1
      Email                mv["Account Name"] + "@panoply.local"                       step 2
      User Principal Name  mv["Email"]                                                 step 3
      Training Summary     "Training " + mv["Training Status"] (HR rule; Training Status
                           comes from the Training Records Source system), ContributeNoValue

    Email -> mail, User Principal Name -> userPrincipalName (Active Directory only; an RFC directory
    has no userPrincipalName) and Training Summary -> physicalDeliveryOfficeName are exported.

    Steps are CUMULATIVE: a named step runs everything up to and including itself.

      Ordering     Initial load. Every person's mail equals Account Name + "@panoply.local" and
                   userPrincipalName equals mail, in the Metaverse and the directory; two same-named
                   joiners carry the same suffix in all three. Training Summary is derived for everyone
                   with a training record (HR synchronised before Training, so it arrives through the
                   mark on the next HR Delta Synchronisation) and absent for everyone without one.
      Stability    A following Full Synchronisation stages no Pending Export and changes no derived value.
      CrossSystem  A Training CSV edit, Training Delta Synchronisation, then HR Delta Synchronisation
                   re-derives Training Summary and exports it. The Training synchronisation alone does
                   not: a derived flow runs only in its hosting system's synchronisation.
      WrongOrder   The same edit with HR synchronised first leaves Training Summary stale for one cycle;
                   the next HR Delta Synchronisation corrects it, because the Training synchronisation
                   marked the HR Connected System Object.
      MissingInput ContributeNoValue over an absent Training Status contributes nothing; once a training
                   record arrives the value follows on the next HR Delta Synchronisation.
      Cycle        A flow closing a dependency cycle across two Synchronisation Rules is refused with 400
                   naming both attributes and both rules, over raw REST and PowerShell alike.
      SurfaceParity Get-JIMSyncRuleMapping round-trips the derived expressions and their step facts,
                   matching raw REST; disabling the generated Account Name flow reports Email and (through
                   Email) User Principal Name as dependent derived flows.

.PARAMETER Step
    Which part to execute (cumulative).

.PARAMETER Template
    Data scale template. Small is the default and the feature's sign-off template.

.PARAMETER JIMUrl
    The URL of the JIM instance (default: http://localhost:5200)

.PARAMETER ApiKey
    API key for authentication

.PARAMETER ContinueOnError
    Continue executing remaining assertions even if one fails.

.PARAMETER SkipPopulate
    Accepted for runner compatibility. The target directory starts empty; JIM provisions every account.

.PARAMETER DirectoryConfig
    Directory configuration hashtable. Defaults to Get-DirectoryConfig -DirectoryType SambaAD.

.EXAMPLE
    ./Invoke-Scenario-026-DerivedAttributeFlows.ps1 -ApiKey "jim_..." -Template Small

.EXAMPLE
    ./Invoke-Scenario-026-DerivedAttributeFlows.ps1 -ApiKey "jim_..." -DirectoryConfig (Get-DirectoryConfig -DirectoryType OpenLDAP -Instance Primary)
#>

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("Ordering", "Stability", "CrossSystem", "WrongOrder", "MissingInput", "Cycle", "SurfaceParity", "All")]
    [string]$Step = "All",

    [Parameter(Mandatory=$false)]
    [string]$Template = "Small",

    [Parameter(Mandatory=$false)]
    [string]$JIMUrl = ($env:JIM_INTEGRATION_URL ?? "http://localhost:5200"),

    [Parameter(Mandatory=$false)]
    [string]$ApiKey,

    [Parameter(Mandatory=$false)]
    [switch]$ContinueOnError,

    [Parameter(Mandatory=$false)]
    [switch]$SkipPopulate,

    [Parameter(Mandatory=$false)]
    [hashtable]$DirectoryConfig
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$ConfirmPreference = 'None'

. "$PSScriptRoot/../utils/Test-Helpers.ps1"
. "$PSScriptRoot/../utils/LDAP-Helpers.ps1"
. "$PSScriptRoot/../utils/Directory-Helpers.ps1"

if (-not $DirectoryConfig) {
    $DirectoryConfig = Get-DirectoryConfig -DirectoryType SambaAD -Instance Primary
}
if (-not $ApiKey) {
    throw "API key required for authentication. Create one via the JIM portal: Admin > API Keys."
}

$isRfcDirectory = Test-IsRfcDirectory $DirectoryConfig
$employeeIdLdapAttr = if ($isRfcDirectory) { 'employeeNumber' } else { 'employeeID' }
$hrCsvPath = "$(Get-IntegrationTestDataPath)/hr-users.csv"
$trainingCsvPath = "$(Get-IntegrationTestDataPath)/training-records.csv"
$emailDomain = "panoply.local"

$script:TestResults = @()
$startTime = Get-Date

function Add-TestResult {
    param(
        [Parameter(Mandatory=$true)][string]$Name,
        [Parameter(Mandatory=$true)][bool]$Passed,
        [Parameter(Mandatory=$false)][string]$Detail = ""
    )
    $script:TestResults += @{ Name = $Name; Passed = $Passed; Detail = $Detail }
    if ($Passed) {
        Write-Host "  ✓ PASSED: $Name" -ForegroundColor Green
    }
    else {
        Write-Host "  ✗ FAILED: $Name" -ForegroundColor Red
        if ($Detail) { Write-Host "      $Detail" -ForegroundColor Yellow }
        if (-not $ContinueOnError) {
            throw "Assertion failed: $Name. $Detail"
        }
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────────────────────

function Get-HeaderValue {
    <#
    .SYNOPSIS
        One attribute off a Metaverse Object header (Get-JIMMetaverseObject -Attributes), $null when the
        object holds no value for it. Reads through PSObject.Properties because an absent attribute is
        an absent property, which strict mode refuses to read directly.
    #>
    param([Parameter(Mandatory=$true)]$Object, [Parameter(Mandatory=$true)][string]$Name)
    if ($null -eq $Object.attributes) { return $null }
    $property = $Object.attributes.PSObject.Properties[$Name]
    if ($property) { return $property.Value }
    return $null
}

function Get-Population {
    <#
    .SYNOPSIS
        Every User Metaverse Object with the attributes this scenario asserts on.
    #>
    return @(Get-JIMMetaverseObject -ObjectTypeName "User" -All -Attributes @(
        "Employee ID", "First Name", "Last Name", "Account Name", "Email", "User Principal Name", "Training Status", "Training Summary"))
}

function Get-Person {
    <#
    .SYNOPSIS
        One person's Metaverse Object header, found by Employee ID.
    #>
    param([Parameter(Mandatory=$true)][string]$EmployeeId)
    $person = @(Get-JIMMetaverseObject -AttributeName "Employee ID" -AttributeValue $EmployeeId -Attributes @(
        "Employee ID", "Account Name", "Email", "User Principal Name", "Training Status", "Training Summary")) | Select-Object -First 1
    Assert-NotNull -Value $person -Message "The Metaverse Object with Employee ID '$EmployeeId' exists"
    return $person
}

function Get-FirstValue {
    param($Entry, [Parameter(Mandatory=$true)][string]$Name)
    if ($null -eq $Entry -or -not $Entry.ContainsKey($Name)) { return $null }
    return @($Entry[$Name])[0]
}

function Get-DirectoryUserMap {
    <#
    .SYNOPSIS
        Every provisioned directory user under the user container, keyed by Employee ID: one search as
        the directory administrator rather than one per person.
    #>
    $entries = @(Find-DirectoryEntry -DirectoryConfig $DirectoryConfig -BaseDn $DirectoryConfig.UserContainer `
        -Filter "($employeeIdLdapAttr=*)" `
        -Attributes @($employeeIdLdapAttr, $DirectoryConfig.UserNameAttr, 'mail', 'userPrincipalName', 'physicalDeliveryOfficeName'))
    $map = @{}
    foreach ($entry in $entries) {
        $id = Get-FirstValue -Entry $entry -Name $employeeIdLdapAttr
        if ($id) { $map[$id] = $entry }
    }
    return $map
}

function Invoke-RunProfileAndAssert {
    param(
        [Parameter(Mandatory=$true)][int]$ConnectedSystemId,
        [Parameter(Mandatory=$true)][int]$RunProfileId,
        [Parameter(Mandatory=$true)][string]$Name
    )
    $result = Start-JIMRunProfile -ConnectedSystemId $ConnectedSystemId -RunProfileId $RunProfileId -Wait -PassThru
    Assert-ActivitySuccess -ActivityId $result.activityId -Name $Name
    return $result
}

function Invoke-HrDelta {
    <#
    .SYNOPSIS
        HR CSV Full Import then HR Delta Synchronisation. The CSV connector has no Delta Import, so the
        import leg is always a Full Import; with the HR CSV unchanged it updates no Connected System Object,
        and the Delta Synchronisation processes only what changed or what another system marked.
    #>
    param([Parameter(Mandatory=$true)][string]$Context)
    Invoke-RunProfileAndAssert -ConnectedSystemId $config.CSVSystemId -RunProfileId $config.CSVImportProfileId -Name "HR CSV Full Import ($Context)" | Out-Null
    Invoke-RunProfileAndAssert -ConnectedSystemId $config.CSVSystemId -RunProfileId $config.CSVDeltaSyncProfileId -Name "HR CSV Delta Synchronisation ($Context)" | Out-Null
}

function Invoke-TrainingDelta {
    param([Parameter(Mandatory=$true)][string]$Context)
    Invoke-RunProfileAndAssert -ConnectedSystemId $config.TrainingSystemId -RunProfileId $config.TrainingImportProfileId -Name "Training Full Import ($Context)" | Out-Null
    Invoke-RunProfileAndAssert -ConnectedSystemId $config.TrainingSystemId -RunProfileId $config.TrainingDeltaSyncProfileId -Name "Training Delta Synchronisation ($Context)" | Out-Null
}

function Invoke-DirectoryExportAndConfirm {
    param([Parameter(Mandatory=$true)][string]$Context)
    Invoke-RunProfileAndAssert -ConnectedSystemId $config.LDAPSystemId -RunProfileId $config.LDAPExportProfileId -Name "Directory Export ($Context)" | Out-Null
    Invoke-RunProfileAndAssert -ConnectedSystemId $config.LDAPSystemId -RunProfileId $config.LDAPDeltaImportProfileId -Name "Directory Delta Import ($Context)" | Out-Null
    Invoke-RunProfileAndAssert -ConnectedSystemId $config.LDAPSystemId -RunProfileId $config.LDAPDeltaSyncProfileId -Name "Directory Delta Synchronisation ($Context)" | Out-Null
}

function Add-HrCsvJoiner {
    <#
    .SYNOPSIS
        Appends one controlled row to hr-users.csv, matching whatever columns the file has (it carries no
        samAccountName, email or userPrincipalName: -OmitItOwnedAttributes).
    #>
    param(
        [Parameter(Mandatory=$true)][string]$EmployeeId,
        [Parameter(Mandatory=$true)][string]$FirstName,
        [Parameter(Mandatory=$true)][string]$LastName,
        [Parameter(Mandatory=$true)][string]$Department
    )

    $csv = @(Import-Csv $hrCsvPath)
    $columns = $csv[0].PSObject.Properties.Name
    $row = [ordered]@{}
    foreach ($col in $columns) {
        $row[$col] = switch ($col) {
            'employeeId'   { $EmployeeId }
            'firstName'    { $FirstName }
            'lastName'     { $LastName }
            'department'   { $Department }
            'title'        { 'Specialist' }
            'company'      { 'Panoply' }
            'displayName'  { "$FirstName $LastName" }
            'status'       { 'Active' }
            'employeeType' { 'Employee' }
            default        { '' }
        }
    }
    $csv += [PSCustomObject]$row
    $csv | Export-Csv -Path $hrCsvPath -NoTypeInformation -Encoding UTF8
    Copy-CsvToConnectorFiles -SourcePath $hrCsvPath
}

function Set-TrainingStatus {
    <#
    .SYNOPSIS
        Changes one person's trainingStatus in training-records.csv, or appends a training record for a
        person who has none (copying the shape of an existing row), and seeds the file into the volume.
    #>
    param(
        [Parameter(Mandatory=$true)][string]$EmployeeId,
        [Parameter(Mandatory=$true)][string]$Status
    )

    $rows = @(Import-Csv $trainingCsvPath)
    $existing = @($rows | Where-Object { $_.employeeId -eq $EmployeeId })
    if ($existing.Count -gt 0) {
        foreach ($row in $existing) { $row.trainingStatus = $Status }
    }
    else {
        $newRow = $rows[0] | Select-Object *
        $newRow.employeeId = $EmployeeId
        $newRow.trainingStatus = $Status
        if ($newRow.PSObject.Properties['samAccountName']) { $newRow.samAccountName = '' }
        $rows += $newRow
    }
    $rows | Export-Csv -Path $trainingCsvPath -NoTypeInformation -Encoding UTF8
    Copy-CsvToConnectorFiles -SourcePath $trainingCsvPath
}

function Get-OtherStatus {
    param([string]$Status)
    if ($Status -eq 'Fail') { return 'Pass' }
    return 'Fail'
}

function Assert-TrainingSummaryInDirectory {
    param([Parameter(Mandatory=$true)][string]$EmployeeId, [Parameter(Mandatory=$true)][string]$Expected, [Parameter(Mandatory=$true)][string]$Context)
    $entry = (Get-DirectoryUserMap)[$EmployeeId]
    $actual = Get-FirstValue -Entry $entry -Name 'physicalDeliveryOfficeName'
    Add-TestResult -Name "[$Context] The re-derived Training Summary reached the directory (physicalDeliveryOfficeName)" `
        -Passed ($actual -eq $Expected) -Detail "Employee $EmployeeId : expected '$Expected', got '$actual'"
}

function Invoke-RawJimApi {
    <#
    .SYNOPSIS
        A raw REST call against the JIM API, deliberately bypassing the JIM PowerShell module, so the
        REST half of a surface-parity assertion does not go through the module's own request building.
        Returns @{ StatusCode; Body; Message } and never throws on an HTTP error status.
    #>
    param(
        [Parameter(Mandatory=$true)][string]$Endpoint,
        [ValidateSet('GET', 'POST', 'PATCH', 'DELETE')][string]$Method = 'GET',
        [object]$Body
    )
    $params = @{
        Uri = "$($JIMUrl.TrimEnd('/'))$Endpoint"
        Method = $Method
        ContentType = 'application/json'
        Headers = @{ 'Accept' = 'application/json'; 'X-API-Key' = $ApiKey }
        SkipHttpErrorCheck = $true
        StatusCodeVariable = 'statusCode'
    }
    if ($Body) { $params.Body = $Body | ConvertTo-Json -Depth 10 }
    $response = Invoke-RestMethod @params
    $message = $null
    if ($response -and $response.PSObject.Properties['message']) { $message = $response.message }
    return @{ StatusCode = [int]$statusCode; Body = $response; Message = $message }
}

# ─────────────────────────────────────────────────────────────────────────────────────────────
# Setup
# ─────────────────────────────────────────────────────────────────────────────────────────────

Write-TestSection "Scenario 026: Metaverse-Derived Attribute Flows"
Write-Host "Directory:   $($DirectoryConfig.ConnectedSystemName) ($($DirectoryConfig.DirectoryType))" -ForegroundColor Gray
Write-Host "Template:    $Template" -ForegroundColor Gray
Write-Host "Step:        $Step (steps are cumulative)" -ForegroundColor Gray
Write-Host ""

Write-TestSection "Step 0: Generating the HR CSV without IT-owned attributes"
& "$PSScriptRoot/../Get-OrGenerate-TestCSV.ps1" -Template $Template -OutputPath "$(Get-IntegrationTestDataPath)" -OmitItOwnedAttributes
Write-Host "  ✓ hr-users.csv generated without samAccountName/email/userPrincipalName" -ForegroundColor Green

Write-TestSection "Step 0b: Configuring JIM (Setup-Scenario-026.ps1)"
$config = & "$PSScriptRoot/../Setup-Scenario-026.ps1" -JIMUrl $JIMUrl -ApiKey $ApiKey -Template $Template -DirectoryConfig $DirectoryConfig
if (-not $config) {
    throw "Setup-Scenario-026.ps1 returned no configuration"
}
Write-Host "  ✓ JIM configured" -ForegroundColor Green

$modulePath = "$PSScriptRoot/../../../src/JIM.PowerShell/JIM.psd1"
Remove-Module JIM -Force -ErrorAction SilentlyContinue
Import-Module $modulePath -Force -ErrorAction Stop
Connect-JIM -Url $JIMUrl -ApiKey $ApiKey | Out-Null

$stepOrder = @("Ordering", "Stability", "CrossSystem", "WrongOrder", "MissingInput", "Cycle", "SurfaceParity")
$lastStepIndex = if ($Step -eq "All") { $stepOrder.Count - 1 } else { $stepOrder.IndexOf($Step) }

# People the later steps edit, chosen once the population exists.
$crossSystemPerson = $null
$wrongOrderPerson = $null

try {
    # ─────────────────────────────────────────────────────────────────────────────────────
    # Ordering (PRD Scenario 1): Account Name, then Email, then User Principal Name in one pass
    # ─────────────────────────────────────────────────────────────────────────────────────
    if ($lastStepIndex -ge $stepOrder.IndexOf("Ordering")) {
        Write-TestSection "Test 1: Ordering (Account Name -> Email -> User Principal Name)"

        # Two same-named joiners, so one of them is suffixed. Each gets its own department because Active
        # Directory builds the DN from CN={Display Name} in an OU per department.
        Add-HrCsvJoiner -EmployeeId "EMP926001" -FirstName "Marisol" -LastName "Fenwick" -Department "Executive"
        Add-HrCsvJoiner -EmployeeId "EMP926002" -FirstName "Marisol" -LastName "Fenwick" -Department "Legal"

        # Initial load in the documented order. HR projects, so it synchronises first; Training only joins,
        # so its synchronisation follows, and marks the HR Connected System Objects whose Training Status it
        # set; the HR Delta Synchronisation then derives Training Summary for exactly those.
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.CSVSystemId -RunProfileId $config.CSVImportProfileId -Name "HR CSV Full Import" | Out-Null
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.TrainingSystemId -RunProfileId $config.TrainingImportProfileId -Name "Training Full Import" | Out-Null
        $hrFullSync = Invoke-RunProfileAndAssert -ConnectedSystemId $config.CSVSystemId -RunProfileId $config.CSVSyncProfileId -Name "HR CSV Full Synchronisation"
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.TrainingSystemId -RunProfileId $config.TrainingSyncProfileId -Name "Training Full Synchronisation" | Out-Null
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.CSVSystemId -RunProfileId $config.CSVDeltaSyncProfileId -Name "HR CSV Delta Synchronisation (marked by Training)" | Out-Null
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.LDAPSystemId -RunProfileId $config.LDAPExportProfileId -Name "Directory Export" | Out-Null
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.LDAPSystemId -RunProfileId $config.LDAPFullImportProfileId -Name "Directory Full Import (confirming)" | Out-Null
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.LDAPSystemId -RunProfileId $config.LDAPFullSyncProfileId -Name "Directory Full Synchronisation (confirming)" | Out-Null

        $people = Get-Population
        $expectedPeople = @(Import-Csv $hrCsvPath).Count
        Add-TestResult -Name "Every HR person was projected" -Passed ($people.Count -eq $expectedPeople) `
            -Detail "Expected $expectedPeople User objects, found $($people.Count)"

        # Metaverse: the three steps of the chain agree for every person.
        $chainMismatches = @()
        foreach ($person in $people) {
            $accountName = Get-HeaderValue -Object $person -Name 'Account Name'
            $email = Get-HeaderValue -Object $person -Name 'Email'
            $upn = Get-HeaderValue -Object $person -Name 'User Principal Name'
            if (-not $accountName -or $email -ne "$accountName@$emailDomain" -or $upn -ne $email) {
                $chainMismatches += "$(Get-HeaderValue -Object $person -Name 'Employee ID'): Account Name '$accountName', Email '$email', User Principal Name '$upn'"
            }
        }
        Add-TestResult -Name "Every person's Email is Account Name + '@$emailDomain' and User Principal Name equals Email (Metaverse, one Full Synchronisation)" `
            -Passed ($chainMismatches.Count -eq 0) -Detail "$($chainMismatches.Count) mismatched: $(($chainMismatches | Select-Object -First 5) -join '; ')"

        # The generated Account Name is unique, so the derived Email and User Principal Name are too.
        $duplicateEmails = @($people | ForEach-Object { Get-HeaderValue -Object $_ -Name 'Email' } | Where-Object { $_ } |
            ForEach-Object { $_.ToLowerInvariant() } | Group-Object | Where-Object { $_.Count -gt 1 })
        Add-TestResult -Name "Derived Email is unique across the population" -Passed ($duplicateEmails.Count -eq 0) `
            -Detail "Duplicates: $(($duplicateEmails | ForEach-Object { $_.Name }) -join ', ')"

        # The same-named pair: one bare, one suffixed, and each person's three values carry their own suffix.
        $marisols = @($people | Where-Object { (Get-HeaderValue -Object $_ -Name 'Employee ID') -in @('EMP926001', 'EMP926002') })
        $marisolNames = @($marisols | ForEach-Object { Get-HeaderValue -Object $_ -Name 'Account Name' } | Sort-Object)
        Add-TestResult -Name "The same-named joiners are 'marisol.fenwick' and 'marisol.fenwick1'" `
            -Passed (($marisolNames -join ',') -eq 'marisol.fenwick,marisol.fenwick1') -Detail "Got: $($marisolNames -join ', ')"

        # Directory: what was exported matches, person by person.
        $directory = Get-DirectoryUserMap
        $directoryMismatches = @()
        foreach ($person in $people) {
            $employeeId = Get-HeaderValue -Object $person -Name 'Employee ID'
            $email = Get-HeaderValue -Object $person -Name 'Email'
            $entry = $directory[$employeeId]
            if (-not $entry) { $directoryMismatches += "${employeeId}: not provisioned"; continue }
            $mail = Get-FirstValue -Entry $entry -Name 'mail'
            if ($mail -ne $email) { $directoryMismatches += "${employeeId}: mail '$mail', Email '$email'" }
            if (-not $isRfcDirectory) {
                $directoryUpn = Get-FirstValue -Entry $entry -Name 'userPrincipalName'
                if ($directoryUpn -ne $mail) { $directoryMismatches += "${employeeId}: userPrincipalName '$directoryUpn', mail '$mail'" }
            }
            $directoryName = Get-FirstValue -Entry $entry -Name $DirectoryConfig.UserNameAttr
            if ("$directoryName@$emailDomain" -ne $mail) { $directoryMismatches += "${employeeId}: $($DirectoryConfig.UserNameAttr) '$directoryName', mail '$mail'" }
        }
        $upnClause = if ($isRfcDirectory) { "" } else { " and userPrincipalName equals mail" }
        Add-TestResult -Name "In the directory every account's mail is its $($DirectoryConfig.UserNameAttr) + '@$emailDomain'$upnClause, including the suffixed joiner" `
            -Passed ($directoryMismatches.Count -eq 0) -Detail "$($directoryMismatches.Count) mismatched: $(($directoryMismatches | Select-Object -First 5) -join '; ')"

        # Training Summary: derived for everyone with a Training Status (through the mark), absent otherwise.
        $summaryMismatches = @()
        $withTraining = 0
        foreach ($person in $people) {
            $status = Get-HeaderValue -Object $person -Name 'Training Status'
            $summary = Get-HeaderValue -Object $person -Name 'Training Summary'
            if ($status) {
                $withTraining++
                if ($summary -ne "Training $status") { $summaryMismatches += "$(Get-HeaderValue -Object $person -Name 'Employee ID'): status '$status', summary '$summary'" }
            }
            elseif ($null -ne $summary) {
                $summaryMismatches += "$(Get-HeaderValue -Object $person -Name 'Employee ID'): no status, summary '$summary'"
            }
        }
        Add-TestResult -Name "Training Summary is derived for the $withTraining people with a Training Status and absent for the rest (ContributeNoValue)" `
            -Passed ($withTraining -gt 0 -and $withTraining -lt $people.Count -and $summaryMismatches.Count -eq 0) `
            -Detail "$($summaryMismatches.Count) mismatched: $(($summaryMismatches | Select-Object -First 5) -join '; ')"

        $officeMismatches = @()
        foreach ($person in $people) {
            $summary = Get-HeaderValue -Object $person -Name 'Training Summary'
            $office = Get-FirstValue -Entry $directory[(Get-HeaderValue -Object $person -Name 'Employee ID')] -Name 'physicalDeliveryOfficeName'
            if ($office -ne $summary) { $officeMismatches += "$(Get-HeaderValue -Object $person -Name 'Employee ID'): summary '$summary', physicalDeliveryOfficeName '$office'" }
        }
        Add-TestResult -Name "Training Summary reached the directory (physicalDeliveryOfficeName) for everyone who has one, and nobody else" `
            -Passed ($officeMismatches.Count -eq 0) -Detail "$($officeMismatches.Count) mismatched: $(($officeMismatches | Select-Object -First 5) -join '; ')"
    }

    # ─────────────────────────────────────────────────────────────────────────────────────
    # Stability (PRD Scenario 6): a following Full Synchronisation stages nothing
    # ─────────────────────────────────────────────────────────────────────────────────────
    if ($lastStepIndex -ge $stepOrder.IndexOf("Stability")) {
        Write-TestSection "Test 2: Stability"

        $before = @{}
        foreach ($person in (Get-Population)) {
            $before[$person.id] = "$(Get-HeaderValue -Object $person -Name 'Email')|$(Get-HeaderValue -Object $person -Name 'User Principal Name')|$(Get-HeaderValue -Object $person -Name 'Training Summary')"
        }
        $pendingBefore = Get-JIMPendingExport -ConnectedSystemId $config.LDAPSystemId -Count

        Invoke-RunProfileAndAssert -ConnectedSystemId $config.CSVSystemId -RunProfileId $config.CSVSyncProfileId -Name "HR CSV Full Synchronisation (stability)" | Out-Null
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.TrainingSystemId -RunProfileId $config.TrainingSyncProfileId -Name "Training Full Synchronisation (stability)" | Out-Null
        Invoke-RunProfileAndAssert -ConnectedSystemId $config.CSVSystemId -RunProfileId $config.CSVDeltaSyncProfileId -Name "HR CSV Delta Synchronisation (stability)" | Out-Null

        $pendingAfter = Get-JIMPendingExport -ConnectedSystemId $config.LDAPSystemId -Count
        Add-TestResult -Name "A following Full Synchronisation stages no Pending Export" -Passed ($pendingAfter -le $pendingBefore) `
            -Detail "Pending Exports before: $pendingBefore, after: $pendingAfter"

        $changed = @()
        foreach ($person in (Get-Population)) {
            $now = "$(Get-HeaderValue -Object $person -Name 'Email')|$(Get-HeaderValue -Object $person -Name 'User Principal Name')|$(Get-HeaderValue -Object $person -Name 'Training Summary')"
            if ($before.ContainsKey($person.id) -and $before[$person.id] -ne $now) { $changed += "$($person.id): '$($before[$person.id])' -> '$now'" }
        }
        Add-TestResult -Name "No derived value changed" -Passed ($changed.Count -eq 0) -Detail (($changed | Select-Object -First 5) -join '; ')
    }

    if ($lastStepIndex -ge $stepOrder.IndexOf("CrossSystem")) {
        # Two people with a training record, chosen deterministically, for the two sequencing steps.
        $trained = @(Get-Population | Where-Object { Get-HeaderValue -Object $_ -Name 'Training Status' } |
            Sort-Object { Get-HeaderValue -Object $_ -Name 'Employee ID' })
        Assert-Condition -Condition ($trained.Count -ge 2) -Message "At least two people have a training record"
        $crossSystemPerson = Get-HeaderValue -Object $trained[0] -Name 'Employee ID'
        $wrongOrderPerson = Get-HeaderValue -Object $trained[1] -Name 'Employee ID'
    }

    # ─────────────────────────────────────────────────────────────────────────────────────
    # Cross-system, correct order (PRD Scenario 2): Training then HR
    # ─────────────────────────────────────────────────────────────────────────────────────
    if ($lastStepIndex -ge $stepOrder.IndexOf("CrossSystem")) {
        Write-TestSection "Test 3: Cross-system input, sources synchronised first"

        $person = Get-Person -EmployeeId $crossSystemPerson
        $oldStatus = Get-HeaderValue -Object $person -Name 'Training Status'
        $newStatus = Get-OtherStatus -Status $oldStatus
        Write-Host "  $crossSystemPerson : Training Status '$oldStatus' -> '$newStatus'" -ForegroundColor Gray
        Set-TrainingStatus -EmployeeId $crossSystemPerson -Status $newStatus

        Invoke-TrainingDelta -Context "cross-system"
        $person = Get-Person -EmployeeId $crossSystemPerson
        Add-TestResult -Name "[CrossSystem] Training's synchronisation updated Training Status" `
            -Passed ((Get-HeaderValue -Object $person -Name 'Training Status') -eq $newStatus) -Detail "Got '$(Get-HeaderValue -Object $person -Name 'Training Status')'"
        Add-TestResult -Name "[CrossSystem] ...but did not evaluate the HR rule's derived flow (it runs only in HR's synchronisation)" `
            -Passed ((Get-HeaderValue -Object $person -Name 'Training Summary') -eq "Training $oldStatus") -Detail "Got '$(Get-HeaderValue -Object $person -Name 'Training Summary')'"

        Invoke-HrDelta -Context "cross-system"
        $person = Get-Person -EmployeeId $crossSystemPerson
        Add-TestResult -Name "[CrossSystem] The HR Delta Synchronisation re-derived Training Summary (the mark selected an unchanged HR object)" `
            -Passed ((Get-HeaderValue -Object $person -Name 'Training Summary') -eq "Training $newStatus") -Detail "Got '$(Get-HeaderValue -Object $person -Name 'Training Summary')'"

        Invoke-DirectoryExportAndConfirm -Context "cross-system"
        Assert-TrainingSummaryInDirectory -EmployeeId $crossSystemPerson -Expected "Training $newStatus" -Context "CrossSystem"
    }

    # ─────────────────────────────────────────────────────────────────────────────────────
    # Cross-system, wrong order (PRD Scenario 2): HR first, stale for one cycle, then corrected
    # ─────────────────────────────────────────────────────────────────────────────────────
    if ($lastStepIndex -ge $stepOrder.IndexOf("WrongOrder")) {
        Write-TestSection "Test 4: Cross-system input, hosting system synchronised first"

        $person = Get-Person -EmployeeId $wrongOrderPerson
        $oldStatus = Get-HeaderValue -Object $person -Name 'Training Status'
        $newStatus = Get-OtherStatus -Status $oldStatus
        Write-Host "  $wrongOrderPerson : Training Status '$oldStatus' -> '$newStatus'" -ForegroundColor Gray
        Set-TrainingStatus -EmployeeId $wrongOrderPerson -Status $newStatus

        # Cycle 1, wrong order: HR, then Training.
        Invoke-HrDelta -Context "wrong order, cycle 1"
        $person = Get-Person -EmployeeId $wrongOrderPerson
        Add-TestResult -Name "[WrongOrder] HR synchronised before Training sees the old Training Status: Training Summary unchanged" `
            -Passed ((Get-HeaderValue -Object $person -Name 'Training Summary') -eq "Training $oldStatus") -Detail "Got '$(Get-HeaderValue -Object $person -Name 'Training Summary')'"

        Invoke-TrainingDelta -Context "wrong order, cycle 1"
        $person = Get-Person -EmployeeId $wrongOrderPerson
        Add-TestResult -Name "[WrongOrder] After cycle 1 Training Status is new and Training Summary is stale (one cycle behind)" `
            -Passed ((Get-HeaderValue -Object $person -Name 'Training Status') -eq $newStatus -and (Get-HeaderValue -Object $person -Name 'Training Summary') -eq "Training $oldStatus") `
            -Detail "Training Status '$(Get-HeaderValue -Object $person -Name 'Training Status')', Training Summary '$(Get-HeaderValue -Object $person -Name 'Training Summary')'"

        # Cycle 2: the HR CSV is unchanged, so only the mark Training set brings this object into HR's delta.
        Invoke-HrDelta -Context "wrong order, cycle 2"
        $person = Get-Person -EmployeeId $wrongOrderPerson
        Add-TestResult -Name "[WrongOrder] The next HR Delta Synchronisation corrects Training Summary (converged one cycle later, not never)" `
            -Passed ((Get-HeaderValue -Object $person -Name 'Training Summary') -eq "Training $newStatus") -Detail "Got '$(Get-HeaderValue -Object $person -Name 'Training Summary')'"

        Invoke-DirectoryExportAndConfirm -Context "wrong order"
        Assert-TrainingSummaryInDirectory -EmployeeId $wrongOrderPerson -Expected "Training $newStatus" -Context "WrongOrder"
    }

    # ─────────────────────────────────────────────────────────────────────────────────────
    # Missing input (PRD Scenario 4): ContributeNoValue, then a value once the input arrives
    # ─────────────────────────────────────────────────────────────────────────────────────
    if ($lastStepIndex -ge $stepOrder.IndexOf("MissingInput")) {
        Write-TestSection "Test 5: Missing input (ContributeNoValue)"

        $untrained = @(Get-Population | Where-Object {
                -not (Get-HeaderValue -Object $_ -Name 'Training Status') -and
                (Get-HeaderValue -Object $_ -Name 'Employee ID') -notin @('EMP926001', 'EMP926002')
            } | Sort-Object { Get-HeaderValue -Object $_ -Name 'Employee ID' })
        Assert-Condition -Condition ($untrained.Count -ge 1) -Message "At least one person has no training record"
        $missingInputPerson = Get-HeaderValue -Object $untrained[0] -Name 'Employee ID'

        Add-TestResult -Name "[MissingInput] With Training Status absent, Training Summary contributes nothing" `
            -Passed ($null -eq (Get-HeaderValue -Object $untrained[0] -Name 'Training Summary')) -Detail "Got '$(Get-HeaderValue -Object $untrained[0] -Name 'Training Summary')'"

        Set-TrainingStatus -EmployeeId $missingInputPerson -Status "InProgress"
        Invoke-TrainingDelta -Context "missing input arrives"
        Invoke-HrDelta -Context "missing input arrives"

        $person = Get-Person -EmployeeId $missingInputPerson
        Add-TestResult -Name "[MissingInput] Once Training Status arrives, the next HR Delta Synchronisation contributes 'Training InProgress'" `
            -Passed ((Get-HeaderValue -Object $person -Name 'Training Summary') -eq "Training InProgress") -Detail "Got '$(Get-HeaderValue -Object $person -Name 'Training Summary')'"

        Invoke-DirectoryExportAndConfirm -Context "missing input arrives"
        Assert-TrainingSummaryInDirectory -EmployeeId $missingInputPerson -Expected "Training InProgress" -Context "MissingInput"
    }

    # ─────────────────────────────────────────────────────────────────────────────────────
    # Cycle (PRD Scenario 3): refused at save, across two Synchronisation Rules
    # ─────────────────────────────────────────────────────────────────────────────────────
    if ($lastStepIndex -ge $stepOrder.IndexOf("Cycle")) {
        Write-TestSection "Test 6: Dependency cycle refused"

        $mvAttributes = @(Get-JIMMetaverseAttribute)
        $probeIds = @{}
        foreach ($name in @("Cycle Probe A", "Cycle Probe B")) {
            $attr = $mvAttributes | Where-Object { $_.name -eq $name } | Select-Object -First 1
            if (-not $attr) {
                $attr = New-JIMMetaverseAttribute -Name $name -Type Text -AttributePlurality SingleValued -ObjectTypeIds @($config.MvUserTypeId)
            }
            $probeIds[$name] = $attr.id
        }

        # Half of the loop on the HR rule: Cycle Probe A reads Cycle Probe B. Nothing contributes B yet, so
        # this saves.
        $probeA = New-JIMSyncRuleMapping -SyncRuleId $config.ImportRuleId -TargetMetaverseAttributeId $probeIds["Cycle Probe A"] `
            -Expression 'mv["Cycle Probe B"]' -ErrorAction Stop
        Add-TestResult -Name "[Cycle] Cycle Probe A = mv[""Cycle Probe B""] saves on the HR rule (no cycle yet)" -Passed ($null -ne $probeA) -Detail ""

        # The other half on the Training rule closes the loop: raw REST first.
        $closingBody = @{
            targetMetaverseAttributeId = $probeIds["Cycle Probe B"]
            sources = @(@{ order = 0; expression = 'mv["Cycle Probe A"]' })
        }
        $rest = Invoke-RawJimApi -Method POST -Endpoint "/api/v1/synchronisation/sync-rules/$($config.TrainingImportRuleId)/mappings" -Body $closingBody
        Add-TestResult -Name "[Cycle] Closing the cycle over raw REST is refused with 400" -Passed ($rest.StatusCode -eq 400) `
            -Detail "Status $($rest.StatusCode): $($rest.Body | ConvertTo-Json -Compress -Depth 5)"
        $restMessage = "$($rest.Message)"
        $named = @("Cycle Probe A", "Cycle Probe B", "HR CSV Import Users", "Training Records Import") | Where-Object { $restMessage -notlike "*$_*" }
        Add-TestResult -Name "[Cycle] The 400 names both attributes and both Synchronisation Rules" -Passed ($restMessage -and @($named).Count -eq 0) `
            -Detail "Missing: $(@($named) -join ', '). Message: $restMessage"

        # ...then through PowerShell, which must relay the same text.
        $psMessage = $null
        try {
            New-JIMSyncRuleMapping -SyncRuleId $config.TrainingImportRuleId -TargetMetaverseAttributeId $probeIds["Cycle Probe B"] `
                -Expression 'mv["Cycle Probe A"]' -ErrorAction Stop | Out-Null
        }
        catch {
            $psMessage = $_.Exception.Message
        }
        Add-TestResult -Name "[Cycle] New-JIMSyncRuleMapping is refused with the same text (HTTP 400)" `
            -Passed ($psMessage -and $restMessage -and $psMessage -match '\(400\)' -and $psMessage.Contains($restMessage)) `
            -Detail "PowerShell: $psMessage"

        $saved = @(Get-JIMSyncRuleMapping -SyncRuleId $config.TrainingImportRuleId | Where-Object { $_.targetMetaverseAttributeId -eq $probeIds["Cycle Probe B"] })
        Add-TestResult -Name "[Cycle] Neither refused attempt saved a mapping" -Passed ($saved.Count -eq 0) -Detail "Found $($saved.Count)"

        # Leave the configuration as it was: the probe has contributed nothing, so there is nothing to recall.
        Remove-JIMSyncRuleMapping -SyncRuleId $config.ImportRuleId -MappingId $probeA.id -Force | Out-Null
    }

    # ─────────────────────────────────────────────────────────────────────────────────────
    # Surface parity (FR 12, FR 3)
    # ─────────────────────────────────────────────────────────────────────────────────────
    if ($lastStepIndex -ge $stepOrder.IndexOf("SurfaceParity")) {
        Write-TestSection "Test 7: Surface parity"

        $psMappings = @(Get-JIMSyncRuleMapping -SyncRuleId $config.ImportRuleId)
        $restResponse = (Invoke-RawJimApi -Endpoint "/api/v1/synchronisation/sync-rules/$($config.ImportRuleId)/mappings").Body
        $restMappings = if ($restResponse -is [array]) { @($restResponse) }
            elseif ($restResponse.PSObject.Properties['items']) { @($restResponse.items) }
            else { @($restResponse) }
        $expected = @(
            @{ Name = "Email";               Expression = 'mv["Account Name"] + "@panoply.local"'; Step = 2; Inputs = "Account Name" }
            @{ Name = "User Principal Name"; Expression = 'mv["Email"]';                           Step = 3; Inputs = "Email" }
            @{ Name = "Training Summary";    Expression = '"Training " + mv["Training Status"]';   Step = 2; Inputs = "Training Status" }
        )
        foreach ($e in $expected) {
            $mappingId = $config.MappingIds[$e.Name]
            $ps = $psMappings | Where-Object { $_.id -eq $mappingId } | Select-Object -First 1
            $rest = $restMappings | Where-Object { $_.id -eq $mappingId } | Select-Object -First 1
            $psExpression = if ($ps) { @($ps.sources)[0].expression } else { $null }
            $restExpression = if ($rest) { @($rest.sources)[0].expression } else { $null }
            $psDerived = if ($ps) { $ps.derived } else { $null }
            $restDerived = if ($rest) { $rest.derived } else { $null }
            $passed = $psExpression -eq $e.Expression -and $restExpression -eq $e.Expression -and
                $psDerived -and $restDerived -and
                $psDerived.step -eq $e.Step -and $restDerived.step -eq $e.Step -and
                $psDerived.stepCount -eq 3 -and $restDerived.stepCount -eq 3 -and
                ((@($psDerived.metaverseInputs) -join ',') -eq $e.Inputs) -and ((@($restDerived.metaverseInputs) -join ',') -eq $e.Inputs)
            Add-TestResult -Name "[SurfaceParity] $($e.Name): expression round-trips and reads as derived, step $($e.Step) of 3, over PowerShell and raw REST" `
                -Passed $passed -Detail "PowerShell: '$psExpression' $($psDerived | ConvertTo-Json -Compress); REST: '$restExpression' $($restDerived | ConvertTo-Json -Compress)"
        }

        $summaryMapping = $psMappings | Where-Object { $_.id -eq $config.MappingIds["Training Summary"] } | Select-Object -First 1
        $behaviour = if ($summaryMapping) { "$(@($summaryMapping.sources)[0].missingInputBehaviour)" } else { $null }
        Add-TestResult -Name "[SurfaceParity] Training Summary's Missing Input Behaviour round-trips as ContributeNoValue" `
            -Passed ($behaviour -in @('ContributeNoValue', '1')) -Detail "Got '$behaviour'"

        # FR 3: disabling the generated Account Name flow takes away Email's only input, and through Email,
        # User Principal Name's. Reported, never blocking; put back straight away (nothing synchronises
        # in between, so no value changes).
        # Warnings are merged into the output stream (3>&1) and split off by type: the cmdlet writes them
        # from a private module function, and redirection catches them wherever they were written.
        $disableOutput = @(Set-JIMSyncRuleMapping -SyncRuleId $config.ImportRuleId -MappingId $config.MappingIds["Account Name"] -Enabled $false -PassThru 3>&1)
        $warnings = @($disableOutput | Where-Object { $_ -is [System.Management.Automation.WarningRecord] } | ForEach-Object { $_.Message })
        $disabled = $disableOutput | Where-Object { $_ -isnot [System.Management.Automation.WarningRecord] } | Select-Object -First 1
        try {
            $dependents = @($disabled.dependentDerivedFlows | Where-Object { $_ })
            $emailDependent = $dependents | Where-Object { $_.mappingId -eq $config.MappingIds["Email"] } | Select-Object -First 1
            $upnDependent = $dependents | Where-Object { $_.mappingId -eq $config.MappingIds["User Principal Name"] } | Select-Object -First 1
            $emailInput = if ($emailDependent) { @($emailDependent.missingInputs)[0] } else { $null }
            $upnInput = if ($upnDependent) { @($upnDependent.missingInputs)[0] } else { $null }

            Add-TestResult -Name "[SurfaceParity] Disabling the Account Name flow reports Email as a dependent derived flow, missing Account Name" `
                -Passed ($emailInput -and $emailInput.metaverseAttributeName -eq 'Account Name' -and -not $emailInput.indirect) `
                -Detail "dependentDerivedFlows: $($dependents | ConvertTo-Json -Compress -Depth 5)"
            Add-TestResult -Name "[SurfaceParity] ...and User Principal Name, missing Account Name through Email" `
                -Passed ($upnInput -and $upnInput.metaverseAttributeName -eq 'Account Name' -and $upnInput.indirect -and ((@($upnInput.via) -join ',') -eq 'Email')) `
                -Detail "dependentDerivedFlows: $($dependents | ConvertTo-Json -Compress -Depth 5)"
            Add-TestResult -Name "[SurfaceParity] ...and nothing that does not read Account Name (Training Summary is not listed)" `
                -Passed (-not ($dependents | Where-Object { $_.mappingId -eq $config.MappingIds["Training Summary"] })) -Detail ""
            Add-TestResult -Name "[SurfaceParity] Set-JIMSyncRuleMapping writes the dependants as warnings" `
                -Passed (@($warnings | Where-Object { "$_" -like "*Email*" }).Count -gt 0 -and @($warnings | Where-Object { "$_" -like "*User Principal Name*" }).Count -gt 0) `
                -Detail "Warnings: $(@($warnings | ForEach-Object { "$_" }) -join ' | ')"
        }
        finally {
            Set-JIMSyncRuleMapping -SyncRuleId $config.ImportRuleId -MappingId $config.MappingIds["Account Name"] -Enabled $true | Out-Null
        }
    }

    Assert-NoWorkerErrors -Since $startTime
}
finally {
    Disconnect-JIM -ErrorAction SilentlyContinue
    Remove-Module JIM -Force -ErrorAction SilentlyContinue
}

# ─────────────────────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────────────────────
$duration = (Get-Date) - $startTime
$passed = @($script:TestResults | Where-Object { $_.Passed }).Count
$failed = @($script:TestResults | Where-Object { -not $_.Passed }).Count

Write-TestSection "Scenario 026 Summary"
Write-Host "Duration: $([math]::Round($duration.TotalSeconds, 1))s" -ForegroundColor Gray
Write-Host "Passed:   $passed" -ForegroundColor Green
if ($failed -gt 0) {
    Write-Host "Failed:   $failed" -ForegroundColor Red
    foreach ($result in $script:TestResults | Where-Object { -not $_.Passed }) {
        Write-Host "  - $($result.Name)" -ForegroundColor Red
    }
    exit 1
}

Write-Host ""
Write-Host "✓ Metaverse-Derived Attribute Flows behave as designed: dependency order, cross-system marking," -ForegroundColor Green
Write-Host "  stability, Missing Input Behaviour, cycle refusal and surface parity all hold." -ForegroundColor Green
exit 0
