// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

using Bunit;
using JIM.Models.Core.DTOs;
using JIM.Web.Shared;
using NUnit.Framework;

namespace JIM.Web.Tests;

/// <summary>
/// Covers SourceDot (#399): a source named quietly by the contribution bar's own group, so its colour and label
/// always match the bar's legend, with the full origin on the title.
/// </summary>
[TestFixture]
public class SourceDotTests : JimComponentTestContext
{
    private static ValueOriginGrouping.Group Group(ValueOrigin origin) =>
        ValueOriginGrouping.BuildGroups([new MetaverseAttributeOriginSummary
        {
            AttributeId = 1,
            AttributeName = "Job Title",
            Origins = [origin]
        }])[0].Group;

    private static readonly ValueOrigin Hr = new()
    {
        Kind = ValueOriginKind.SynchronisationRule,
        ConnectedSystemId = 1,
        ConnectedSystemName = "HR",
        SyncRuleId = 5,
        SyncRuleName = "HR Import Users"
    };

    [Test]
    public void SourceDot_ShowRule_RendersTheBarColourTheLabelAndTheRule()
    {
        var cut = Render<SourceDot>(p => p.Add(c => c.Group, Group(Hr)).Add(c => c.ShowRule, true));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(cut.Find(".jim-source-dot").GetAttribute("style"), Does.Contain("var(--mud-palette-info)"));
            Assert.That(cut.Find(".jim-source-dot-name").TextContent, Is.EqualTo("HR"));
            Assert.That(cut.Find(".jim-source-dot-rule").TextContent, Is.EqualTo("HR Import Users"));
            Assert.That(cut.Find(".jim-source-dot-label").GetAttribute("title"), Is.EqualTo("HR · HR Import Users"));
        }
    }

    [Test]
    public void SourceDot_WithoutShowRule_NamesTheSystemOnlyAndKeepsTheRuleOnTheTitle()
    {
        var cut = Render<SourceDot>(p => p.Add(c => c.Group, Group(Hr)));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(cut.FindAll(".jim-source-dot-rule"), Is.Empty);
            Assert.That(cut.Find(".jim-source-dot-label").GetAttribute("title"), Is.EqualTo("HR · HR Import Users"));
        }
    }

    [Test]
    public void SourceDot_GeneratedByJim_TakesThePrimaryColourAndSaysSoOnTheTitle()
    {
        var generated = Hr with { Kind = ValueOriginKind.GeneratedByJim };

        var cut = Render<SourceDot>(p => p.Add(c => c.Group, Group(generated)));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(cut.Find(".jim-source-dot").GetAttribute("style"), Does.Contain("var(--mud-palette-primary)"));
            Assert.That(cut.Find(".jim-source-dot-label").GetAttribute("title"), Is.EqualTo("Generated by JIM · HR · HR Import Users"));
        }
    }

    [Test]
    public void SourceDot_NotRecorded_TakesTheNeutralColour()
    {
        var cut = Render<SourceDot>(p => p.Add(c => c.Group, Group(ValueOrigin.NotRecorded)).Add(c => c.ShowRule, true));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(cut.Find(".jim-source-dot").GetAttribute("style"), Does.Contain("var(--mud-palette-text-disabled)"));
            Assert.That(cut.Find(".jim-source-dot-name").TextContent, Is.EqualTo("Source not recorded"));
            Assert.That(cut.FindAll(".jim-source-dot-rule"), Is.Empty);
        }
    }
}
