// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

using Bunit;
using JIM.Models.Core.DTOs;
using JIM.Web.Shared;
using MudBlazor;
using NUnit.Framework;

namespace JIM.Web.Tests;

/// <summary>
/// Covers the one shared rendering of a Metaverse Object attribute value's origin (#399): every kind of
/// <see cref="ValueOrigin"/> the contract can produce, plus the "several origins" and "not recorded" cases, so
/// the Inspect view's Source column and the attribute inspector can never disagree about how an origin reads.
/// </summary>
[TestFixture]
public class ValueOriginChipTests : JimComponentTestContext
{
    [Test]
    public void ValueOriginChip_SynchronisationRule_RendersConnectedSystemChipAndRuleLink()
    {
        var origin = new ValueOrigin
        {
            Kind = ValueOriginKind.SynchronisationRule,
            ConnectedSystemId = 4,
            ConnectedSystemName = "HR",
            SyncRuleId = 9,
            SyncRuleName = "HR Import"
        };

        var cut = Render<ValueOriginChip>(p => p.Add(c => c.Origin, origin));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(cut.FindComponent<ObjectChip>().Instance.Name, Is.EqualTo("HR"));
            Assert.That(cut.FindComponent<ObjectChip>().Instance.Kind, Is.EqualTo(ObjectChipKind.ConnectedSystem));
            // Two links exist (the Connected System chip and the rule); find the rule's by its href.
            var link = RuleLink(cut);
            Assert.That(link.TextContent, Is.EqualTo("HR Import"));
            Assert.That(link.GetAttribute("href"), Is.EqualTo("/admin/sync-rules/9"));
        }
    }

    private static AngleSharp.Dom.IElement RuleLink(IRenderedComponent<ValueOriginChip> cut) =>
        cut.FindAll("a").First(a => a.GetAttribute("href")!.Contains("/sync-rules/"));

    [Test]
    public void ValueOriginChip_SynchronisationRuleDeleted_RendersLowLightedTextWithNoLink()
    {
        var origin = new ValueOrigin
        {
            Kind = ValueOriginKind.SynchronisationRule,
            ConnectedSystemId = 4,
            ConnectedSystemName = "Facilities",
            SyncRuleId = null,
            SyncRuleName = null,
            SyncRuleDeleted = true
        };

        var cut = Render<ValueOriginChip>(p => p.Add(c => c.Origin, origin));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(cut.Markup, Does.Contain("rule deleted"));
            // The Connected System chip may still legitimately be a link; the deleted rule itself must not be.
            Assert.That(cut.FindAll("a").Any(a => a.GetAttribute("href")!.Contains("/sync-rules/")), Is.False);
        }
    }

    [Test]
    public void ValueOriginChip_AssertsNoValue_AppendsAssertsNoValueText()
    {
        var origin = new ValueOrigin
        {
            Kind = ValueOriginKind.SynchronisationRule,
            ConnectedSystemId = 4,
            ConnectedSystemName = "HR",
            SyncRuleId = 9,
            SyncRuleName = "HR Import",
            AssertsNoValue = true
        };

        var cut = Render<ValueOriginChip>(p => p.Add(c => c.Origin, origin));

        Assert.That(cut.Markup, Does.Contain("asserts no value"));
    }

    [Test]
    public void ValueOriginChip_GeneratedByJimWithCorrected_RendersPrimaryChipRouteAndWarningChip()
    {
        var origin = new ValueOrigin
        {
            Kind = ValueOriginKind.GeneratedByJim,
            ConnectedSystemId = 4,
            ConnectedSystemName = "HR",
            SyncRuleId = 9,
            SyncRuleName = "HR Import",
            Corrected = true
        };

        var cut = Render<ValueOriginChip>(p => p.Add(c => c.Origin, origin));

        var chips = cut.FindComponents<MudChip<string>>();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(chips, Has.Count.EqualTo(2));
            Assert.That(chips[0].Instance.Color, Is.EqualTo(Color.Primary));
            Assert.That(cut.Markup, Does.Contain("Generated by JIM"));
            Assert.That(chips[1].Instance.Color, Is.EqualTo(Color.Warning));
            Assert.That(cut.Markup, Does.Contain("Corrected"));
            Assert.That(cut.FindComponent<ObjectChip>().Instance.Name, Is.EqualTo("HR"));
            Assert.That(RuleLink(cut).TextContent, Is.EqualTo("HR Import"));
        }
    }

    [Test]
    public void ValueOriginChip_GeneratedByJimWithNoRoute_RendersOnlyThePrimaryChip()
    {
        var origin = new ValueOrigin { Kind = ValueOriginKind.GeneratedByJim };

        var cut = Render<ValueOriginChip>(p => p.Add(c => c.Origin, origin));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(cut.Markup, Does.Contain("Generated by JIM"));
            Assert.That(cut.HasComponent<ObjectChip>(), Is.False);
        }
    }

    [Test]
    public void ValueOriginChip_SetByPerson_RendersSetByPersonName()
    {
        var origin = new ValueOrigin { Kind = ValueOriginKind.SetByPerson, PersonName = "Priya Shah" };

        var cut = Render<ValueOriginChip>(p => p.Add(c => c.Origin, origin));

        Assert.That(cut.Markup, Does.Contain("Set by Priya Shah"));
    }

    [Test]
    public void ValueOriginChip_NotRecorded_RendersLowLightedSourceNotRecorded()
    {
        var cut = Render<ValueOriginChip>(p => p.Add(c => c.Origin, ValueOrigin.NotRecorded));

        Assert.That(cut.Markup, Does.Contain("Source not recorded"));
    }

    [Test]
    public void ValueOriginChip_HasSeveralOrigins_RendersSeveralSourcesRatherThanTheGivenOrigin()
    {
        var origin = new ValueOrigin
        {
            Kind = ValueOriginKind.SynchronisationRule,
            ConnectedSystemId = 4,
            ConnectedSystemName = "HR",
            SyncRuleId = 9,
            SyncRuleName = "HR Import"
        };

        var cut = Render<ValueOriginChip>(p => p
            .Add(c => c.Origin, origin)
            .Add(c => c.HasSeveralOrigins, true));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(cut.Markup, Does.Contain("Several sources"));
            Assert.That(cut.HasComponent<ObjectChip>(), Is.False, "the several-origins case must not name one of them");
        }
    }
}
