// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

using Asp.Versioning;
using JIM.Application;
using JIM.Models.Transactional;
using JIM.Models.Transactional.DTOs;
using JIM.Web.Models.Api;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JIM.Web.Controllers.Api;

/// <summary>
/// API controller for generated values held for an administrator's decision (Unique Value Generation, #242, release 4):
/// a target rejected a generated value as already in use, and Collision Remediation did not correct it because another
/// Connected System has already accepted it, because JIM cannot tell whether one has, or because it has been corrected as
/// often as JIM allows. The export carrying it is held until someone allows the rename, tries again, or changes the
/// Attribute Flow.
/// </summary>
/// <remarks>
/// Both actions change only JIM's own records (they release the held export for the next export run to pick up), so they
/// complete within the request and answer <c>200 OK</c> with the value as it now stands, rather than <c>202 Accepted</c>
/// with a task to follow: there is nothing queued to wait for. Every action is recorded as an Activity naming the user or
/// API key that took it.
/// </remarks>
[Route("api/v{version:apiVersion}/generated-values")]
[ApiController]
[ApiVersion("1.0")]
[Authorize(Roles = "Administrator")]
[Produces("application/json")]
public class GeneratedValuesController(ILogger<GeneratedValuesController> logger, JimApplication application) : ApiControllerBase(application, logger)
{
    private readonly ILogger<GeneratedValuesController> _logger = logger;
    private readonly JimApplication _application = application;

    /// <summary>
    /// List generated values held for a decision
    /// </summary>
    /// <remarks>
    /// Returns values that need a decision and values whose rename has been allowed and is waiting for the next export,
    /// newest first. Corrected values need no action and are not listed; their history is on their Metaverse Object.
    ///
    /// Criteria combine: `?connectedSystemId=3&amp;status=NeedsDecision` is "values involving Connected System 3 that need
    /// a decision". A value involves a Connected System when that system rejected it, anchors it, or the value is exported
    /// to and checked in it.
    /// </remarks>
    /// <param name="pagination">Page and page size; sorting is fixed (newest first).</param>
    /// <param name="connectedSystemId">Optional. Restrict to values involving one Connected System.</param>
    /// <param name="syncRuleId">Optional. Restrict to values generated by one Synchronisation Rule's Attribute Flows.</param>
    /// <param name="status">Optional. `NeedsDecision` or `RenameAllowed`; omit for both.</param>
    /// <param name="metaverseObjectId">Optional. Restrict to one Metaverse Object's values, including those on accounts joined to it.</param>
    /// <response code="200">The requested page of held values.</response>
    /// <response code="400">An unparseable filter value, or `status=Released`, which a list never holds.</response>
    /// <response code="404">No such Connected System or Synchronisation Rule.</response>
    [HttpGet("decisions", Name = "GetGeneratedValueDecisions")]
    [ProducesResponseType(typeof(PaginatedResponse<GeneratedValueDecisionDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetDecisionsAsync(
        [FromQuery] PaginationRequest pagination,
        [FromQuery] int? connectedSystemId = null,
        [FromQuery] int? syncRuleId = null,
        [FromQuery] GeneratedValueDecisionStatus? status = null,
        [FromQuery] Guid? metaverseObjectId = null)
    {
        ArgumentNullException.ThrowIfNull(pagination);

        if (status == GeneratedValueDecisionStatus.Released)
            return BadRequest(ApiErrorResponse.BadRequest("A list holds only values that need a decision or have their rename allowed; status may be NeedsDecision or RenameAllowed."));

        var notFound = await FindMissingFilterTargetAsync(connectedSystemId, syncRuleId);
        if (notFound != null)
            return notFound;

        var filter = new GeneratedValueDecisionFilter
        {
            ConnectedSystemId = connectedSystemId,
            SyncRuleId = syncRuleId,
            Status = status,
            MetaverseObjectId = metaverseObjectId
        };

        var result = await _application.GeneratedValueDecisions.GetDecisionsAsync(filter, pagination.Skip, pagination.PageSize, includeTotalCount: true);
        var items = result.Results.Select(GeneratedValueDecisionDto.FromHeader).ToList();

        return Ok(PaginatedResponse<GeneratedValueDecisionDto>.Create(items, result.TotalResults ?? items.Count, pagination.Page, pagination.PageSize));
    }

    /// <summary>
    /// Summarise generated values held for a decision
    /// </summary>
    /// <remarks>
    /// Counts values that need a decision, values whose rename has been allowed, and values Collision Remediation
    /// corrected in the last 7 days (`correctedRecentlyCount`, from `correctedSince`). A corrected value counts once, from
    /// its most recent correction, while it still exists.
    /// </remarks>
    /// <param name="connectedSystemId">Optional. Count only values involving one Connected System.</param>
    /// <param name="syncRuleId">Optional. Count only values generated by one Synchronisation Rule's Attribute Flows.</param>
    /// <response code="200">The counts.</response>
    /// <response code="404">No such Connected System or Synchronisation Rule.</response>
    [HttpGet("decisions/summary", Name = "GetGeneratedValueDecisionSummary")]
    [ProducesResponseType(typeof(GeneratedValueDecisionSummary), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetDecisionSummaryAsync([FromQuery] int? connectedSystemId = null, [FromQuery] int? syncRuleId = null)
    {
        var notFound = await FindMissingFilterTargetAsync(connectedSystemId, syncRuleId);
        if (notFound != null)
            return notFound;

        return Ok(await _application.GeneratedValueDecisions.GetSummaryAsync(connectedSystemId, syncRuleId));
    }

    /// <summary>
    /// Get one generated value's decision
    /// </summary>
    /// <remarks>
    /// Returns the value whatever its state, so `status` may also be `Released`: nothing is waiting on a decision for it.
    /// </remarks>
    /// <param name="id">The generated value's id.</param>
    /// <response code="200">The value.</response>
    /// <response code="404">No generated value has this id; it may have been deleted with its object or its Attribute Flow.</response>
    [HttpGet("decisions/{id:guid}", Name = "GetGeneratedValueDecision")]
    [ProducesResponseType(typeof(GeneratedValueDecisionDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetDecisionAsync(Guid id)
    {
        var row = await _application.GeneratedValueDecisions.GetDecisionAsync(id);
        return row == null
            ? NotFound(ApiErrorResponse.NotFound($"Generated value {id} was not found."))
            : Ok(GeneratedValueDecisionDto.FromHeader(row));
    }

    /// <summary>
    /// Allow the rename of a held generated value
    /// </summary>
    /// <remarks>
    /// Authorises JIM, at the next export that meets the rejection, to choose the next free value and apply it everywhere
    /// the value is used, renaming the account in the Connected System that already holds the current value. The new
    /// value is decided then, after JIM checks every system again, not now. The held export is released so that export
    /// happens. Recorded as an Activity naming who allowed it.
    /// </remarks>
    /// <param name="id">The generated value's id.</param>
    /// <response code="200">The value as it now stands (`status` is `RenameAllowed`).</response>
    /// <response code="404">No generated value has this id.</response>
    /// <response code="409">The value is not waiting on a decision (already released, or its rename already allowed).</response>
    [HttpPost("{id:guid}/allow-rename", Name = "AllowGeneratedValueRename")]
    [ProducesResponseType(typeof(GeneratedValueDecisionDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status409Conflict)]
    public Task<IActionResult> AllowRenameAsync(Guid id) =>
        ActAsync(id, "allow the rename",
            (decisions, initiatedBy, apiKey) => decisions.AllowRenameAsync(id, initiatedBy, apiKey));

    /// <summary>
    /// Try a held generated value again
    /// </summary>
    /// <remarks>
    /// Releases the held export so the next export run tries the same value, for when the clash has been resolved in the
    /// target. If the target rejects it again, it is held for a decision again. Recorded as an Activity naming who
    /// released it.
    /// </remarks>
    /// <param name="id">The generated value's id.</param>
    /// <response code="200">The value as it now stands (`status` is `Released`).</response>
    /// <response code="404">No generated value has this id.</response>
    /// <response code="409">The value is not waiting on a decision.</response>
    [HttpPost("{id:guid}/try-again", Name = "TryGeneratedValueAgain")]
    [ProducesResponseType(typeof(GeneratedValueDecisionDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status409Conflict)]
    public Task<IActionResult> TryAgainAsync(Guid id) =>
        ActAsync(id, "try again",
            (decisions, initiatedBy, apiKey) => decisions.TryAgainAsync(id, initiatedBy, apiKey));

    /// <summary>
    /// Try every matching held generated value again
    /// </summary>
    /// <remarks>
    /// Releases every value matching the request that needs a decision, so the next export run tries each again. Values
    /// whose rename has been allowed are left as they are. Each released value is recorded as its own Activity.
    /// </remarks>
    /// <param name="request">Which values. Must name at least one criterion, or set `applyToAllDecisions`.</param>
    /// <response code="200">How many values were released. Zero is a valid outcome, not an error.</response>
    /// <response code="400">The request names no values, or names more than may be listed in one request.</response>
    /// <response code="404">No such Connected System or Synchronisation Rule.</response>
    [HttpPost("decisions/try-again", Name = "TryGeneratedValueDecisionsAgain")]
    [ProducesResponseType(typeof(GeneratedValueDecisionActionResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ApiErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> TryAgainForDecisionsAsync([FromBody] GeneratedValueDecisionActionRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        var notFound = await FindMissingFilterTargetAsync(request.ConnectedSystemId, request.SyncRuleId);
        if (notFound != null)
            return notFound;

        var (initiatedBy, apiKey, unauthorised) = await IdentifyCallerAsync("try again");
        if (unauthorised != null)
            return unauthorised;

        _logger.LogInformation(
            "Generated value bulk try again requested (Connected System: {ConnectedSystemId}, Synchronisation Rule: {SyncRuleId}, Named values: {NamedValues})",
            request.ConnectedSystemId, request.SyncRuleId, request.Ids?.Count ?? 0);

        var released = await _application.GeneratedValueDecisions.TryAgainAsync(request.ToFilter(), initiatedBy, apiKey);
        return Ok(new GeneratedValueDecisionActionResponse { AffectedCount = released });
    }

    private async Task<IActionResult> ActAsync(
        Guid id,
        string actionName,
        Func<Application.Servers.GeneratedValueDecisionServer, JIM.Models.Core.MetaverseObject?, JIM.Models.Security.ApiKey?, Task<GeneratedValueDecisionActionOutcome>> action)
    {
        var (initiatedBy, apiKey, unauthorised) = await IdentifyCallerAsync(actionName);
        if (unauthorised != null)
            return unauthorised;

        var outcome = await action(_application.GeneratedValueDecisions, initiatedBy, apiKey);
        switch (outcome)
        {
            case GeneratedValueDecisionActionOutcome.NotFound:
                return NotFound(ApiErrorResponse.NotFound($"Generated value {id} was not found."));
            case GeneratedValueDecisionActionOutcome.NotWaitingForDecision:
                return Conflict(ApiErrorResponse.Conflict($"Generated value {id} is not waiting on a decision, so there is nothing to {actionName}."));
        }

        var row = await _application.GeneratedValueDecisions.GetDecisionAsync(id);
        return row == null
            ? NotFound(ApiErrorResponse.NotFound($"Generated value {id} was not found."))
            : Ok(GeneratedValueDecisionDto.FromHeader(row));
    }

    /// <summary>
    /// Every decision is attributed: an administrator at a screen, or the API key an automation presented.
    /// </summary>
    private async Task<(JIM.Models.Core.MetaverseObject? User, JIM.Models.Security.ApiKey? ApiKey, IActionResult? Unauthorised)> IdentifyCallerAsync(string actionName)
    {
        var initiatedBy = await GetCurrentUserAsync();
        var apiKey = await GetCurrentApiKeyAsync();
        if (initiatedBy != null || apiKey != null)
            return (initiatedBy, apiKey, null);

        _logger.LogWarning("Could not identify the caller of a generated value {ActionName}", actionName);
        return (null, null, Unauthorized(ApiErrorResponse.Unauthorised("Could not identify user from authentication token.")));
    }

    private async Task<IActionResult?> FindMissingFilterTargetAsync(int? connectedSystemId, int? syncRuleId)
    {
        if (connectedSystemId.HasValue && await _application.ConnectedSystems.GetConnectedSystemCoreAsync(connectedSystemId.Value) == null)
            return NotFound(ApiErrorResponse.NotFound($"Connected System {connectedSystemId.Value} was not found."));

        if (syncRuleId.HasValue && await _application.ConnectedSystems.GetSyncRuleAsync(syncRuleId.Value) == null)
            return NotFound(ApiErrorResponse.NotFound($"Synchronisation Rule {syncRuleId.Value} was not found."));

        return null;
    }
}
