// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

using System.ComponentModel.DataAnnotations.Schema;
using JIM.Models.Transactional;

namespace JIM.Models.Staging;

/// <summary>
/// Whether, and how, a Connected System receives synchronised passwords (#1119).
/// <para>
/// Held on the Connected System rather than on a Synchronisation Rule, which is the opposite of where an initial
/// password lives (<see cref="JIM.Models.Logic.SyncRuleInitialPassword"/>), and deliberately so. An initial
/// password is generated by JIM for a population a rule defines, so different rules can reasonably want different
/// ones. A synchronised password is the person's own: there is one of it, and every system they have an account
/// in should end up holding it. What varies between systems is not the password but whether the system takes it
/// at all and how hard JIM should try, which is a property of the system.
/// </para>
/// <para>
/// A row exists only for a system somebody has configured; its absence is requirement 1's unconfigured state,
/// with no separate flag needed to say so. Existing deployments therefore upgrade with Password Synchronisation
/// off everywhere and no behaviour changed.
/// </para>
/// <para>
/// Note what is deliberately absent: how the password should behave once set. A synchronised password is one the
/// person chose, so requiring them to change it again at the target would defeat the purpose of synchronising it;
/// delivery always lets the target apply its own expiry policy. The per-change
/// <see cref="PasswordExpiryBehaviour"/> stays on the request, where an administrator setting a password on
/// somebody's behalf can still ask for a change at next sign-in.
/// </para>
/// </summary>
public class ConnectedSystemPasswordSynchronisation
{
    /// <summary>
    /// How many delivery attempts JIM makes before parking a queued password change, when the configuration does
    /// not say. Five attempts under the default backoff spans roughly two and a half hours, which rides out a
    /// restart or a brief outage without leaving an obviously-broken target being retried all week.
    /// </summary>
    public const int DefaultMaxRetries = 5;

    /// <summary>
    /// The first retry interval, doubled for each subsequent attempt, when the configuration does not say.
    /// </summary>
    public static readonly TimeSpan DefaultRetryBackoffBase = TimeSpan.FromMinutes(5);

    public int Id { get; set; }

    public ConnectedSystem ConnectedSystem { get; set; } = null!;

    public int ConnectedSystemId { get; set; }

    /// <summary>
    /// Whether queued password changes are delivered to this system.
    /// <para>
    /// Separate from the row's existence (requirement 2) so that a system can be configured ahead of a change
    /// window and switched on during it. A configured but disabled system still accumulates queued changes rather
    /// than discarding them, and enabling it drains what accumulated without an administrator having to do
    /// anything further (requirement 3). That is the whole reason the toggle is not simply "delete the
    /// configuration": deleting it would throw away the queue.
    /// </para>
    /// </summary>
    public bool Enabled { get; set; }

    /// <summary>
    /// The Connected System Object Type that receives passwords, i.e. whichever type holds this system's user
    /// accounts.
    /// <para>
    /// Fan-out needs it to decide which of an identity's accounts in this system is the one to set a password on;
    /// an identity may well have a Connected System Object of another type in the same system.
    /// </para>
    /// </summary>
    public ConnectedSystemObjectType TargetObjectType { get; set; } = null!;

    public int TargetObjectTypeId { get; set; }

    /// <summary>
    /// How many delivery attempts to make before parking the change for an administrator. Zero or less is treated
    /// as unconfigured; see <see cref="EffectiveMaxRetries"/>.
    /// </summary>
    public int MaxRetries { get; set; } = DefaultMaxRetries;

    /// <summary>
    /// The first retry interval; each subsequent attempt waits twice as long as the one before. Zero or less is
    /// treated as unconfigured; see <see cref="EffectiveRetryBackoffBase"/>.
    /// </summary>
    public TimeSpan RetryBackoffBase { get; set; } = DefaultRetryBackoffBase;

    /// <summary>
    /// Whether JIM must refuse to transmit a password to this system over a connection it cannot confirm is
    /// encrypted.
    /// <para>
    /// Off by default, and that default is a considered position rather than laxity. The LDAP Connector warns on
    /// an unencrypted connection instead of blocking, because a signed and sealed bind is a legitimate encrypted
    /// alternative that JIM cannot detect from the Connected System's settings alone, so blocking on the settings
    /// would refuse a valid configuration. This setting is how an administrator who knows their deployment closes
    /// that gap: turning it on makes the refusal the Connector's behaviour for this system.
    /// </para>
    /// </summary>
    public bool RequireSecureTransport { get; set; }

    /// <summary>
    /// The retry ceiling actually applied. A value of zero or less is treated as unconfigured rather than obeyed,
    /// because "deliver once and then park" is a state the queue can already reach by exhausting its retries, and
    /// obeying a zero here would make a row nobody had thought about behave as though somebody had chosen it.
    /// </summary>
    [NotMapped]
    public int EffectiveMaxRetries => MaxRetries > 0 ? MaxRetries : DefaultMaxRetries;

    /// <summary>
    /// The backoff base actually applied. Zero or less is treated as unconfigured rather than obeyed: a zero base
    /// retries continuously against a system that is already refusing us.
    /// </summary>
    [NotMapped]
    public TimeSpan EffectiveRetryBackoffBase =>
        RetryBackoffBase > TimeSpan.Zero ? RetryBackoffBase : DefaultRetryBackoffBase;

    /// <summary>
    /// How long to wait before the next delivery attempt, given how many have already been made.
    /// </summary>
    /// <param name="attemptCount">Attempts made so far. Anything below one is treated as the first attempt.</param>
    /// <param name="timeToLive">
    /// The queued change's own time to live, which caps the delay: scheduling a retry beyond the point at which
    /// the change expires would book an attempt against something that will not exist to attempt. Zero or less is
    /// treated as unconfigured and falls back to JIM's default window, mirroring
    /// <see cref="ConnectedSystem.EffectiveInitialPasswordTimeToLive"/>.
    /// </param>
    public TimeSpan CalculateRetryDelay(int attemptCount, TimeSpan timeToLive)
    {
        var cap = timeToLive > TimeSpan.Zero ? timeToLive : PendingInitialPassword.DefaultTimeToLive;

        // Computed in seconds rather than by doubling ticks, so that a large attempt count saturates to infinity
        // and clamps to the cap instead of overflowing.
        var scaledSeconds = EffectiveRetryBackoffBase.TotalSeconds * Math.Pow(2, Math.Max(attemptCount, 1) - 1);

        return scaledSeconds >= cap.TotalSeconds ? cap : TimeSpan.FromSeconds(scaledSeconds);
    }

    /// <summary>
    /// A detached copy of everything <see cref="WouldDeliverTheSameAs"/> compares, for holding what was saved
    /// while an editor mutates the live instance in place. The identity and navigation are deliberately left off:
    /// this is a value to compare against, never something to persist.
    /// </summary>
    public ConnectedSystemPasswordSynchronisation SnapshotDeliverySettings()
    {
        return new ConnectedSystemPasswordSynchronisation
        {
            Enabled = Enabled,
            TargetObjectTypeId = TargetObjectTypeId,
            MaxRetries = MaxRetries,
            RetryBackoffBase = RetryBackoffBase,
            RequireSecureTransport = RequireSecureTransport
        };
    }

    /// <summary>
    /// Whether two configurations would deliver the same way, and therefore whether saving one over the other is
    /// worth setting parked password changes retrying.
    /// <para>
    /// Parking stops the retry loop because something about this configuration, or about the target, made another
    /// identical attempt pointless. Only a change to the configuration makes one worth making again, and saving an
    /// unrelated edit must not set parked changes retrying against settings the target has already answered on.
    /// </para>
    /// <para>
    /// A null on either side is a real state, not a missing value: it means the system does not receive
    /// synchronised passwords, and switching that on or off is itself a change of delivery.
    /// </para>
    /// <para>
    /// <c>ConnectedSystemPasswordSynchronisationTests</c> fails if a setting is added to this class without being
    /// compared here, because a setting nobody compared would silently stop releasing parked work when it changed.
    /// </para>
    /// </summary>
    public static bool WouldDeliverTheSameAs(
        ConnectedSystemPasswordSynchronisation? left,
        ConnectedSystemPasswordSynchronisation? right)
    {
        if (left == null || right == null)
            return left == null && right == null;

        return left.Enabled == right.Enabled &&
               left.TargetObjectTypeId == right.TargetObjectTypeId &&
               left.MaxRetries == right.MaxRetries &&
               left.RetryBackoffBase == right.RetryBackoffBase &&
               left.RequireSecureTransport == right.RequireSecureTransport;
    }

    public override string ToString()
    {
        return $"{nameof(ConnectedSystemPasswordSynchronisation)}: Connected System {ConnectedSystemId} " +
               $"({(Enabled ? "enabled" : "disabled")})";
    }
}
