#!/bin/bash
# Copyright (c) Tetron Limited. All rights reserved.
# Licensed under the Tetron Commercial License. See LICENSE file in the project root.
# Post-provisioning setup for Samba AD
# This script runs after the domain is provisioned to add TLS and test OUs
# Called by Build-SambaImages.ps1 after the container is running and healthy
#
# ARCHITECTURE: Supports both AMD64 and ARM64 via diegogslomp/samba-ad-dc base image

set -e

echo "=============================================="
echo "Post-provisioning Samba AD Configuration"
echo "=============================================="

# Parse domain components from environment
# diegogslomp/samba-ad-dc uses REALM for full domain (e.g., TESTDOMAIN.LOCAL)
# and DOMAIN for short domain (e.g., TESTDOMAIN)
FULL_DOMAIN=${REALM:-${DOMAIN}}
LDOMAIN=${FULL_DOMAIN,,}
UDOMAIN=${FULL_DOMAIN^^}
URDOMAIN=${UDOMAIN%%.*}

# Build the DC string (e.g., PANOPLY.LOCAL -> DC=panoply,DC=local)
DOMAIN_DC=$(echo "$LDOMAIN" | sed 's/\./,DC=/g' | sed 's/^/DC=/')

echo "Domain: ${FULL_DOMAIN}"
echo "Domain DN: ${DOMAIN_DC}"

# diegogslomp/samba-ad-dc paths (different from nowsci/samba-domain)
SAMBA_BASE="/usr/local/samba"
SAMBA_PRIVATE="${SAMBA_BASE}/private"
SAMBA_ETC="${SAMBA_BASE}/etc"
SAMBA_BIN="${SAMBA_BASE}/bin"

echo "Samba base path: ${SAMBA_BASE}"

# Create symlinks for common samba commands so they work without full paths
# This makes scripts compatible with both old (nowsci) and new (diegogslomp) images
echo "Creating symlinks for samba commands..."
for cmd in samba-tool smbclient ldbsearch ldbadd ldbmodify ldbedit; do
    if [ -f "${SAMBA_BIN}/${cmd}" ] && [ ! -f "/usr/bin/${cmd}" ]; then
        ln -sf "${SAMBA_BIN}/${cmd}" "/usr/bin/${cmd}" 2>/dev/null || true
    fi
done
echo "  Symlinks created"

# Generate TLS certificates for LDAPS
echo "Generating TLS certificates for LDAPS..."
mkdir -p ${SAMBA_PRIVATE}/tls

# Samba autogenerates its own TLS certificate ("temporary autogenerated HOST certificate") at first
# start, and the build script waits for Samba to be fully up before running this script, so a
# certificate always exists here. It carries only the DC's FQDN, which is not enough (see below), so
# it must be replaced unconditionally: a previous existence guard here baked Samba's autogenerated
# certificate into every image, and the SAN check in Add-SambaCertificateToJimStore then failed each
# scenario run no matter how often the image was rebuilt.
rm -f ${SAMBA_PRIVATE}/tls/cert.pem ${SAMBA_PRIVATE}/tls/key.pem ${SAMBA_PRIVATE}/tls/ca.pem

# The certificate must carry every name JIM might connect by, because certificate validation is
# always on and there is no option to skip it.
#
# Three names matter, and a certificate naming only the domain (which is what this generated before)
# covers none of the other two:
#   - the domain controller's own FQDN, which is what it advertises as its dNSHostName and what JIM
#     pins to after discovering it. Without this, every AD-family run logs "JIM could not open a
#     connection to that name, so it has not been pinned" and falls back, losing consistent delta
#     imports.
#   - the Docker Compose service name, which is the Host an administrator configures on the
#     Connected System and the name the first connection is made to.
#   - the domain itself, kept for anything addressing the directory by domain name.
DC_SHORT_NAME="$(hostname -s)"
DC_FQDN="${DC_SHORT_NAME}.${LDOMAIN}"
CERT_SANS="DNS:${DC_FQDN},DNS:${DC_SHORT_NAME},DNS:${LDOMAIN}"

# The Compose service name cannot be derived inside the container, so the build script passes it in.
if [ -n "${SAMBA_CERT_EXTRA_NAMES}" ]; then
    for extra_name in $(echo "${SAMBA_CERT_EXTRA_NAMES}" | tr ',' ' '); do
        CERT_SANS="${CERT_SANS},DNS:${extra_name}"
    done
fi

echo "  Certificate names: ${CERT_SANS}"

openssl req -x509 -nodes -days 3650 \
    -newkey rsa:2048 \
    -keyout ${SAMBA_PRIVATE}/tls/key.pem \
    -out ${SAMBA_PRIVATE}/tls/cert.pem \
    -subj "/CN=${DC_FQDN}/O=JIM Integration Testing" \
    -addext "subjectAltName=${CERT_SANS}" \
    2>/dev/null

cp ${SAMBA_PRIVATE}/tls/cert.pem ${SAMBA_PRIVATE}/tls/ca.pem
chmod 600 ${SAMBA_PRIVATE}/tls/key.pem
echo "  TLS certificates generated"

# Add TLS configuration to smb.conf if not present
if ! grep -q "tls enabled" ${SAMBA_ETC}/smb.conf; then
    echo "Adding TLS configuration to smb.conf..."
    sed -i "/\[global\]/a \\
tls enabled = yes\\n\\
tls keyfile = ${SAMBA_PRIVATE}/tls/key.pem\\n\\
tls certfile = ${SAMBA_PRIVATE}/tls/cert.pem\\n\\
tls cafile = ${SAMBA_PRIVATE}/tls/ca.pem\\n\\
ldap server require strong auth = no\\
" ${SAMBA_ETC}/smb.conf
    echo "  TLS configuration added"
else
    echo "  TLS already configured"
fi

# Configure domain password policy. This must always run and must fail the build if it
# cannot apply: these settings are baked into the committed image, and the test
# credentials must never expire. This block was previously gated on NOCOMPLEXITY (which
# is only set on the committed image, never during the build's docker exec) with all
# failures suppressed, so --max-pwd-age=0 silently never applied; published images kept
# the 42-day default and every Samba AD integration test started failing 44 days after
# the image build with "The supplied credential is invalid".
echo "Configuring domain password policy..."
${SAMBA_BIN}/samba-tool domain passwordsettings set --complexity=off
${SAMBA_BIN}/samba-tool domain passwordsettings set --history-length=0
${SAMBA_BIN}/samba-tool domain passwordsettings set --min-pwd-age=0
${SAMBA_BIN}/samba-tool domain passwordsettings set --max-pwd-age=0

# Belt and braces: mark the Administrator password itself as never expiring
# (userAccountControl 512 -> 66048 adds DONT_EXPIRE_PASSWD 0x10000), so the credential
# survives even if the domain policy is ever reset to defaults.
echo "Setting DONT_EXPIRE_PASSWD on Administrator..."
cat > /tmp/admin-uac.ldif << EOF
dn: CN=Administrator,CN=Users,${DOMAIN_DC}
changetype: modify
replace: userAccountControl
userAccountControl: 66048
EOF
${SAMBA_BIN}/ldbmodify -H ${SAMBA_PRIVATE}/sam.ldb /tmp/admin-uac.ldif
rm -f /tmp/admin-uac.ldif

# Verify both settings actually applied; read them back rather than trusting exit codes.
echo "Verifying password policy..."
max_age=$(${SAMBA_BIN}/samba-tool domain passwordsettings show | grep "Maximum password age" | grep -o '[0-9]*$')
if [ "${max_age}" != "0" ]; then
    echo "ERROR: Maximum password age is '${max_age}', expected 0; the Administrator credential would expire" >&2
    exit 1
fi
admin_uac=$(${SAMBA_BIN}/ldbsearch -H ${SAMBA_PRIVATE}/sam.ldb -b "CN=Administrator,CN=Users,${DOMAIN_DC}" -s base userAccountControl | grep '^userAccountControl:' | awk '{print $2}')
if [ $(( admin_uac & 65536 )) -eq 0 ]; then
    echo "ERROR: Administrator userAccountControl is '${admin_uac}'; DONT_EXPIRE_PASSWD (0x10000) not set" >&2
    exit 1
fi
echo "  Password policy verified (max age 0, Administrator password never expires)"

# Create baseline OU structure for integration testing
# These OUs are created here (during post-provisioning) so they're baked into
# the committed image. This runs AFTER the container is running, so the database
# exists and will be persisted by docker commit.
#
# Structure:
#   OU=Corp,DC=...              - Main corporate structure (selected in JIM)
#     OU=Users,OU=Corp,DC=...   - User objects (provisioned here by JIM)
#     OU=Groups,OU=Corp,DC=...  - Group objects
#   OU=TestUsers,DC=...         - Legacy test users (for compatibility)
#   OU=TestGroups,DC=...        - Legacy test groups
echo "Creating baseline OU structure..."

# Corp base OU - this is selected as the partition container in JIM
${SAMBA_BIN}/samba-tool ou create "OU=Corp,${DOMAIN_DC}" 2>/dev/null || echo "  OU=Corp already exists"
${SAMBA_BIN}/samba-tool ou create "OU=Users,OU=Corp,${DOMAIN_DC}" 2>/dev/null || echo "  OU=Users,OU=Corp already exists"
${SAMBA_BIN}/samba-tool ou create "OU=Groups,OU=Corp,${DOMAIN_DC}" 2>/dev/null || echo "  OU=Groups,OU=Corp already exists"

# Legacy test OUs (kept for backward compatibility with Populate-SambaAD.ps1)
${SAMBA_BIN}/samba-tool ou create "OU=TestUsers,${DOMAIN_DC}" 2>/dev/null || echo "  OU=TestUsers already exists"
${SAMBA_BIN}/samba-tool ou create "OU=TestGroups,${DOMAIN_DC}" 2>/dev/null || echo "  OU=TestGroups already exists"

echo "  OU structure created"

# ==============================================================================
# JIM's service account and its delegation
# ==============================================================================
# Integration scenarios connect JIM's Connected Systems as this account, never as the domain
# Administrator: every run then exercises the permissions a customer delegates rather than an
# identity that bypasses access control entirely. The lab's own population and assertions keep
# using the Administrator credential; see engineering/INTEGRATION_TESTING.md for the two-identity
# model, and docs/connectors/jim-ldap-connector.md for the delegation as customers are told to
# apply it (the same access control entries, from the same file).
JIM_SERVICE_PASSWORD="${JIM_SERVICE_PASSWORD:-Svc-Jim@123!}"
JIM_SERVICE_DN="CN=svc-jim,OU=Services,${DOMAIN_DC}"

echo "Creating JIM's service account..."
${SAMBA_BIN}/samba-tool ou create "OU=Services,${DOMAIN_DC}" 2>/dev/null || echo "  OU=Services already exists"
${SAMBA_BIN}/samba-tool user create svc-jim "${JIM_SERVICE_PASSWORD}" --userou="OU=Services" \
    --description="The account JIM's Connected Systems bind as" 2>/dev/null || echo "  svc-jim already exists"
${SAMBA_BIN}/samba-tool group create "JIM Connectors" --groupou="OU=Services" 2>/dev/null || echo "  Group 'JIM Connectors' already exists"
${SAMBA_BIN}/samba-tool group addmembers "JIM Connectors" svc-jim 2>/dev/null || true
echo "  svc-jim created, in group 'JIM Connectors'"

# The credential is baked into a long-lived image, so it must never expire, for the same reason
# the Administrator credential above must not.
cat > /tmp/svc-jim-uac.ldif << EOF
dn: ${JIM_SERVICE_DN}
changetype: modify
replace: userAccountControl
userAccountControl: 66048
EOF
${SAMBA_BIN}/ldbmodify -H ${SAMBA_PRIVATE}/sam.ldb /tmp/svc-jim-uac.ldif
rm -f /tmp/svc-jim-uac.ldif

# Samba creates the Deleted Objects container on the domain's first deletion, so a freshly
# provisioned domain has nothing to delegate read over yet. One throwaway account, created and
# deleted, brings the container into being.
${SAMBA_BIN}/samba-tool user create jim-tombstone-seed "${JIM_SERVICE_PASSWORD}" --userou="OU=Services" > /dev/null
${SAMBA_BIN}/samba-tool user delete jim-tombstone-seed > /dev/null

echo "Delegating JIM's access over the managed containers..."
for jim_container_dn in "OU=Corp,${DOMAIN_DC}" "OU=TestUsers,${DOMAIN_DC}" "OU=TestGroups,${DOMAIN_DC}"; do
    /usr/local/sbin/jim-delegate.sh "${jim_container_dn}"
done
/usr/local/sbin/jim-delegate.sh --tombstones

# Prove the delegation works before the image is committed: a lab whose service account cannot
# do what JIM needs would fail every scenario with an access error, hours later and far from the
# cause. Each probe is one of JIM's operations, performed over LDAP as svc-jim.
echo "Verifying the delegation..."
JIM_PROBE_DN="CN=Delegation Probe,OU=Users,OU=Corp,${DOMAIN_DC}"
jim_as_service_account() {
    ${SAMBA_BIN}/"$@" -H ldap://localhost --simple-bind-dn="${JIM_SERVICE_DN}" --password="${JIM_SERVICE_PASSWORD}"
}

cat > /tmp/jim-probe-add.ldif << EOF
dn: ${JIM_PROBE_DN}
changetype: add
objectClass: user
sAMAccountName: jim-probe
userAccountControl: 514
displayName: Delegation Probe
EOF
if ! jim_as_service_account ldbadd /tmp/jim-probe-add.ldif > /dev/null; then
    echo "ERROR: svc-jim could not create a user in OU=Users,OU=Corp; the delegation did not apply" >&2
    exit 1
fi

cat > /tmp/jim-probe-mod.ldif << EOF
dn: ${JIM_PROBE_DN}
changetype: modify
replace: department
department: Delegation
EOF
if ! jim_as_service_account ldbmodify /tmp/jim-probe-mod.ldif > /dev/null; then
    echo "ERROR: svc-jim could not write an attribute on a user it created" >&2
    exit 1
fi

# Setting a password is granted by the Reset Password control access right, which is separate
# from attribute write access, so it is checked separately. samba-tool signs and seals this
# connection, which is what Active Directory insists on for a password write.
if ! ${SAMBA_BIN}/samba-tool user setpassword jim-probe --newpassword="Probe@12345!" \
        -H ldap://localhost -U "svc-jim%${JIM_SERVICE_PASSWORD}" > /dev/null 2>&1; then
    echo "ERROR: svc-jim could not set a password; the Reset Password right did not apply" >&2
    exit 1
fi

# The reset-rights preflight reads the object's own permissions, with the security descriptor
# flags control, and reports that it could not tell if they come back empty.
probe_sd=$(jim_as_service_account ldbsearch --controls="sd_flags:1:7" -b "${JIM_PROBE_DN}" -s base nTSecurityDescriptor 2>/dev/null | grep -c "^nTSecurityDescriptor:")
if [ "${probe_sd}" != "1" ]; then
    echo "ERROR: svc-jim could not read nTSecurityDescriptor on a user; the reset-rights preflight would report an unknown" >&2
    exit 1
fi

if ! jim_as_service_account ldbdel "${JIM_PROBE_DN}" > /dev/null; then
    echo "ERROR: svc-jim could not delete the user it created" >&2
    exit 1
fi

# The delete just made a tombstone. A Delta Import finds it in the Deleted Objects container,
# and an account without rights there is told nothing rather than refused, so this check is the
# only thing standing between a silent delegation gap and deletions never being imported.
tombstones=$(jim_as_service_account ldbsearch --controls="show_deleted:1" -b "CN=Deleted Objects,${DOMAIN_DC}" -s one "(isDeleted=TRUE)" dn 2>/dev/null | grep -c "^dn:")
if [ "${tombstones}" -lt 1 ]; then
    echo "ERROR: svc-jim read no tombstones from the Deleted Objects container; Delta Import would silently miss every deletion" >&2
    exit 1
fi

# And the other half of least privilege: the account must not be able to write where JIM is not
# managing anything, nor hold administrative rights by the back door.
cat > /tmp/jim-probe-outside.ldif << EOF
dn: CN=Should Not Exist,CN=Users,${DOMAIN_DC}
changetype: add
objectClass: user
sAMAccountName: jim-probe-outside
userAccountControl: 514
EOF
if jim_as_service_account ldbadd /tmp/jim-probe-outside.ldif > /dev/null 2>&1; then
    echo "ERROR: svc-jim created a user in CN=Users, outside the containers it was delegated; the delegation is too broad" >&2
    exit 1
fi
if ${SAMBA_BIN}/samba-tool group listmembers "Domain Admins" 2>/dev/null | grep -q "^svc-jim$"; then
    echo "ERROR: svc-jim is a member of Domain Admins; the lab would prove nothing about delegated access" >&2
    exit 1
fi
rm -f /tmp/jim-probe-add.ldif /tmp/jim-probe-mod.ldif /tmp/jim-probe-outside.ldif
echo "  Delegation verified (create, write, set password, read permissions, delete, read tombstones; no access outside)"

# Install SSH public key schema (optional, may already exist)
echo "Checking SSH public key schema..."
sshkey_check=$(${SAMBA_BIN}/ldbsearch -H ${SAMBA_PRIVATE}/sam.ldb "cn=sshPublicKey" 2>/dev/null || true)
if ! echo "$sshkey_check" | grep -q sshPublicKey 2>/dev/null; then
    echo "Installing SSH public key schema..."

    echo "dn: CN=sshPublicKey,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.3.6.1.4.1.24552.500.1.1.1.13
cn: sshPublicKey
name: sshPublicKey
lDAPDisplayName: sshPublicKey
description: MANDATORY: OpenSSH Public key
attributeSyntax: 2.5.5.10
oMSyntax: 4
isSingleValued: FALSE
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 8
schemaIDGUID:: cjDAZyEXzU+/akI0EGDW+g==" > /tmp/sshpubkey.attr.ldif

    echo "dn: CN=ldapPublicKey,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: classSchema
governsID: 1.3.6.1.4.1.24552.500.1.1.2.0
cn: ldapPublicKey
name: ldapPublicKey
description: MANDATORY: OpenSSH LPK objectclass
lDAPDisplayName: ldapPublicKey
subClassOf: top
objectClassCategory: 3
objectCategory: CN=Class-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
defaultObjectCategory: CN=ldapPublicKey,CN=Schema,CN=Configuration,${DOMAIN_DC}
mayContain: sshPublicKey
schemaIDGUID:: +8nFQ43rpkWTOgbCCcSkqA==" > /tmp/sshpubkey.class.ldif

    ${SAMBA_BIN}/ldbadd -H ${SAMBA_PRIVATE}/sam.ldb /tmp/sshpubkey.attr.ldif --option="dsdb:schema update allowed"=true 2>/dev/null || true
    ${SAMBA_BIN}/ldbadd -H ${SAMBA_PRIVATE}/sam.ldb /tmp/sshpubkey.class.ldif --option="dsdb:schema update allowed"=true 2>/dev/null || true
    rm -f /tmp/sshpubkey.*.ldif
    echo "  SSH public key schema installed"
else
    echo "  SSH public key schema already exists"
fi

# Install Exchange extensionAttribute1-15 schema (for integration testing)
# In real AD these come from the Exchange schema extension. We add them to Samba AD
# so integration tests can use extensionAttribute1-15 on user objects (e.g., for
# storing pronouns, custom HR data, etc.)
#
# OIDs and schemaIdGUIDs sourced from Microsoft Exchange Server SDK documentation:
# https://learn.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2003/
echo "Checking extensionAttribute schema..."
extattr_check=$(${SAMBA_BIN}/ldbsearch -H ${SAMBA_PRIVATE}/sam.ldb "cn=ms-Exch-Extension-Attribute-1" 2>/dev/null || true)
if ! echo "$extattr_check" | grep -q "ms-Exch-Extension-Attribute-1" 2>/dev/null; then
    echo "Installing extensionAttribute1-15 schema..."

    # Attribute definitions (1-10: rangeUpper 1024, 11-15: rangeUpper 2048)
    # All are single-valued Unicode strings (attributeSyntax 2.5.5.12, oMSyntax 64)
    cat > /tmp/extattr.ldif << EXTATTR_EOF
dn: CN=ms-Exch-Extension-Attribute-1,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.423
cn: ms-Exch-Extension-Attribute-1
name: ms-Exch-Extension-Attribute-1
lDAPDisplayName: extensionAttribute1
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: Z3mWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-2,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.424
cn: ms-Exch-Extension-Attribute-2
name: ms-Exch-Extension-Attribute-2
lDAPDisplayName: extensionAttribute2
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: aXmWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-3,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.425
cn: ms-Exch-Extension-Attribute-3
name: ms-Exch-Extension-Attribute-3
lDAPDisplayName: extensionAttribute3
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: anmWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-4,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.426
cn: ms-Exch-Extension-Attribute-4
name: ms-Exch-Extension-Attribute-4
lDAPDisplayName: extensionAttribute4
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: a3mWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-5,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.427
cn: ms-Exch-Extension-Attribute-5
name: ms-Exch-Extension-Attribute-5
lDAPDisplayName: extensionAttribute5
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: bHmWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-6,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.428
cn: ms-Exch-Extension-Attribute-6
name: ms-Exch-Extension-Attribute-6
lDAPDisplayName: extensionAttribute6
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: bXmWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-7,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.429
cn: ms-Exch-Extension-Attribute-7
name: ms-Exch-Extension-Attribute-7
lDAPDisplayName: extensionAttribute7
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: bnmWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-8,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.430
cn: ms-Exch-Extension-Attribute-8
name: ms-Exch-Extension-Attribute-8
lDAPDisplayName: extensionAttribute8
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: b3mWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-9,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.431
cn: ms-Exch-Extension-Attribute-9
name: ms-Exch-Extension-Attribute-9
lDAPDisplayName: extensionAttribute9
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: cHmWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-10,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.432
cn: ms-Exch-Extension-Attribute-10
name: ms-Exch-Extension-Attribute-10
lDAPDisplayName: extensionAttribute10
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 1024
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: aHmWv+YN0BGihQCqADBJ4g==

dn: CN=ms-Exch-Extension-Attribute-11,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.599
cn: ms-Exch-Extension-Attribute-11
name: ms-Exch-Extension-Attribute-11
lDAPDisplayName: extensionAttribute11
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 2048
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: 9ld3FvNH0RGpwwAA+ANnwQ==

dn: CN=ms-Exch-Extension-Attribute-12,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.600
cn: ms-Exch-Extension-Attribute-12
name: ms-Exch-Extension-Attribute-12
lDAPDisplayName: extensionAttribute12
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 2048
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: 91d3FvNH0RGpwwAA+ANnwQ==

dn: CN=ms-Exch-Extension-Attribute-13,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.601
cn: ms-Exch-Extension-Attribute-13
name: ms-Exch-Extension-Attribute-13
lDAPDisplayName: extensionAttribute13
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 2048
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: +Fd3FvNH0RGpwwAA+ANnwQ==

dn: CN=ms-Exch-Extension-Attribute-14,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.602
cn: ms-Exch-Extension-Attribute-14
name: ms-Exch-Extension-Attribute-14
lDAPDisplayName: extensionAttribute14
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 2048
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: +Vd3FvNH0RGpwwAA+ANnwQ==

dn: CN=ms-Exch-Extension-Attribute-15,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: add
objectClass: top
objectClass: attributeSchema
attributeID: 1.2.840.113556.1.2.603
cn: ms-Exch-Extension-Attribute-15
name: ms-Exch-Extension-Attribute-15
lDAPDisplayName: extensionAttribute15
attributeSyntax: 2.5.5.12
oMSyntax: 64
isSingleValued: TRUE
rangeLower: 1
rangeUpper: 2048
objectCategory: CN=Attribute-Schema,CN=Schema,CN=Configuration,${DOMAIN_DC}
searchFlags: 16
schemaIDGUID:: +ld3FvNH0RGpwwAA+ANnwQ==
EXTATTR_EOF

    # Load all 15 attribute definitions into the schema
    ${SAMBA_BIN}/ldbadd -H ${SAMBA_PRIVATE}/sam.ldb /tmp/extattr.ldif \
        --option="dsdb:schema update allowed"=true 2>/dev/null || true

    # Add extensionAttribute1-15 as mayContain on the user class
    # This allows user objects to carry these attributes (mimics Exchange schema extension)
    cat > /tmp/extattr-user.ldif << EXTATTR_USER_EOF
dn: CN=User,CN=Schema,CN=Configuration,${DOMAIN_DC}
changetype: modify
add: mayContain
mayContain: extensionAttribute1
mayContain: extensionAttribute2
mayContain: extensionAttribute3
mayContain: extensionAttribute4
mayContain: extensionAttribute5
mayContain: extensionAttribute6
mayContain: extensionAttribute7
mayContain: extensionAttribute8
mayContain: extensionAttribute9
mayContain: extensionAttribute10
mayContain: extensionAttribute11
mayContain: extensionAttribute12
mayContain: extensionAttribute13
mayContain: extensionAttribute14
mayContain: extensionAttribute15
EXTATTR_USER_EOF

    ${SAMBA_BIN}/ldbmodify -H ${SAMBA_PRIVATE}/sam.ldb /tmp/extattr-user.ldif \
        --option="dsdb:schema update allowed"=true 2>/dev/null || true

    rm -f /tmp/extattr.ldif /tmp/extattr-user.ldif
    echo "  extensionAttribute1-15 schema installed"
else
    echo "  extensionAttribute schema already exists"
fi

echo "=============================================="
echo "Post-provisioning complete!"
echo "=============================================="
