# Copyright (c) Tetron Limited. All rights reserved.
# Licensed under the Tetron Commercial License. See LICENSE file in the project root.

function Get-JIMMetaverseObjectConnection {
    <#
    .SYNOPSIS
        Explains why a Metaverse Object is connected where it is, and why it is not connected elsewhere.

    .DESCRIPTION
        Returns one object per Connected System Object joined to the Metaverse Object: how it was
        joined (method, Synchronisation Rule, date and Activity) and the scoping of every relevant
        enabled Synchronisation Rule, evaluated now against current values.

        With -IncludeNotConnected, also returns one object per enabled export Synchronisation Rule
        whose Connected System holds no object joined to this one, with the reason (NotInScope,
        ProvisioningDisabled, RuleMisconfigured or NotYetProvisioned), a one-line hint, what would
        change it, and a plain-text summary to paste into a ticket. The words are generated by JIM
        and are the ones the portal's Connections tab shows.

        Every object has the same top-level properties, so connections and not-connected entries can
        be listed, filtered and sorted together. Values of credential attributes are withheld.

    .PARAMETER Id
        The unique identifier (GUID) of the Metaverse Object. Accepts pipeline input from
        Get-JIMMetaverseObject.

    .PARAMETER ConnectedSystemName
        Returns only the entries for the Connected System with this name (an exact,
        case-insensitive match). Errors when nothing matches.

    .PARAMETER IncludeNotConnected
        Also explains the enabled export Synchronisation Rules whose Connected System holds no
        object joined to this Metaverse Object.

    .OUTPUTS
        One PSCustomObject per entry, with:
        MetaverseObjectId, MetaverseObjectName, ConnectedSystem (the Connected System's name),
        ConnectedSystemId, Connected ($true for a joined connection, $false for a not-connected
        entry), Object (the joined Connected System Object's external id; empty when not
        connected), ConnectedSystemObjectId, ObjectType, Role (Source, Target, Source and Target or
        None), State (the connection state, such as InSync or UpdatePending, or the not-connected
        reason), SyncRule (the export Synchronisation Rule of a not-connected entry), Join (for a
        connection: JoinType, Method, DateJoined, SyncRuleId, SyncRuleName, Source, Description,
        ActivityId, RunProfileExecutionItemId), Hint, BulletsTitle, Bullets (plain-text lines),
        Summary, Scoping (one explanation per Synchronisation Rule, each with SyncRuleName,
        Direction, Outcome, Hint, Groups and Criteria, a flat list of every criterion with Path,
        Met, Outcome, AttributeName, ComparisonType, Expected, Actual, ValueCount, Description and
        ActualDescription), Conflicts (export rules that cannot connect because this connection
        holds the slot) and EvaluatedAt (UTC).

    .EXAMPLE
        Get-JIMMetaverseObjectConnection -Id "12345678-1234-1234-1234-123456789abc" -IncludeNotConnected |
            Format-Table ConnectedSystem, Connected, State, Hint

        Lists where the Metaverse Object is connected, and why it is not connected elsewhere.

    .EXAMPLE
        (Get-JIMMetaverseObjectConnection -Id $mvoId -IncludeNotConnected -ConnectedSystemName "Finance App").Summary

        Prints the plain-text explanation of why the Metaverse Object is not in Finance App, ready to
        paste into a ticket.

    .EXAMPLE
        Get-JIMMetaverseObjectConnection -Id $mvoId -IncludeNotConnected |
            ForEach-Object { $_.Scoping } |
            ForEach-Object { $_.Criteria } |
            Where-Object { -not $_.Met } |
            Format-Table Path, Description, ActualDescription

        Lists every scoping criterion the Metaverse Object currently fails, across all its rules.

    .EXAMPLE
        Get-JIMMetaverseObject -AttributeName "Account Name" -AttributeValue jsmith |
            Get-JIMMetaverseObjectConnection |
            Format-Table ConnectedSystem, Object, @{ Name = 'Joined'; Expression = { $_.Join.Description } }

        Pipes a Metaverse Object into the cmdlet to see how each of its connections was joined.

    .LINK
        Get-JIMMetaverseObject

    .LINK
        Get-JIMMetaverseObjectProvenance

    .LINK
        Get-JIMSyncRule
    #>
    [CmdletBinding()]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory, ValueFromPipelineByPropertyName)]
        [Guid]$Id,

        [ValidateNotNullOrEmpty()]
        [string]$ConnectedSystemName,

        [switch]$IncludeNotConnected
    )

    process {
        if (-not $script:JIMConnection) {
            Write-Error "You are not connected to JIM. Run Connect-JIM -Url <your JIM URL> to authenticate, then try again."
            return
        }

        $endpoint = "/api/v1/metaverse/objects/$Id/connections"
        if ($IncludeNotConnected) {
            $endpoint += '?includeNotConnected=true'
        }

        Write-Verbose "Getting connection explanations for Metaverse Object $Id"
        $response = Invoke-JIMApi -Endpoint $endpoint
        if (-not $response) {
            # Invoke-JIMApi already wrote the error (e.g. Metaverse Object not found).
            return
        }

        $entries = [System.Collections.Generic.List[object]]::new()

        foreach ($connection in $response.Connections) {
            $role = if ($connection.IsSource -and $connection.IsTarget) { 'Source and Target' }
                    elseif ($connection.IsSource) { 'Source' }
                    elseif ($connection.IsTarget) { 'Target' }
                    else { 'None' }

            $entries.Add([PSCustomObject]@{
                MetaverseObjectId       = $response.MetaverseObjectId
                MetaverseObjectName     = $response.DisplayName
                ConnectedSystem         = $connection.ConnectedSystemName
                ConnectedSystemId       = $connection.ConnectedSystemId
                Connected               = $true
                Object                  = $connection.DisplayName
                ConnectedSystemObjectId = $connection.ConnectedSystemObjectId
                ObjectType              = $connection.ObjectTypeName
                Role                    = $role
                State                   = $connection.State
                SyncRule                = $null
                Join                    = $connection.Join
                Hint                    = $null
                BulletsTitle            = $null
                Bullets                 = @()
                Summary                 = $null
                Scoping                 = @($connection.Scoping)
                Conflicts               = @($connection.Conflicts)
                EvaluatedAt             = $response.EvaluatedAt
            })
        }

        foreach ($entry in $response.NotConnected) {
            $entries.Add([PSCustomObject]@{
                MetaverseObjectId       = $response.MetaverseObjectId
                MetaverseObjectName     = $response.DisplayName
                ConnectedSystem         = $entry.ConnectedSystemName
                ConnectedSystemId       = $entry.ConnectedSystemId
                Connected               = $false
                Object                  = $null
                ConnectedSystemObjectId = $null
                ObjectType              = $entry.ObjectTypeName
                Role                    = 'Target'
                State                   = $entry.Reason
                SyncRule                = $entry.SyncRuleName
                Join                    = $null
                Hint                    = $entry.Hint
                BulletsTitle            = $entry.BulletsTitle
                Bullets                 = @($entry.Bullets | ForEach-Object { $_.Text })
                Summary                 = $entry.Summary
                Scoping                 = @($entry.Scoping)
                Conflicts               = @()
                EvaluatedAt             = $response.EvaluatedAt
            })
        }

        if ($PSBoundParameters.ContainsKey('ConnectedSystemName')) {
            $matched = @($entries | Where-Object { $_.ConnectedSystem -eq $ConnectedSystemName })
            if ($matched.Count -eq 0) {
                $hint = if ($IncludeNotConnected) { '' } else { ' Add -IncludeNotConnected to include Connected Systems it is not connected to.' }
                Write-Error "No connection to a Connected System named '$ConnectedSystemName' was found for Metaverse Object $Id.$hint"
                return
            }
            return $matched
        }

        $entries
    }
}
