#!/bin/bash
set -e

echo "🚀 Setting up JIM development environment..."
echo ""

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_step() {
    echo -e "${BLUE}▶${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# 1. Install .NET EF Core tools
print_step "Installing .NET Entity Framework Core tools..."
if ! dotnet tool list -g | grep -q dotnet-ef; then
    dotnet tool install --global dotnet-ef
    print_success "dotnet-ef installed globally"
else
    # Try to update, but don't fail if it errors (can happen in some environments)
    if dotnet tool update --global dotnet-ef 2>/dev/null; then
        print_success "dotnet-ef updated to latest version"
    else
        print_warning "dotnet-ef update skipped (already installed)"
    fi
fi

# Add .NET tools to PATH
export PATH="$PATH:$HOME/.dotnet/tools"
echo 'export PATH="$PATH:$HOME/.dotnet/tools"' >> ~/.zshrc
echo 'export PATH="$PATH:$HOME/.dotnet/tools"' >> ~/.bashrc

# 2. Restore NuGet packages
print_step "Restoring NuGet packages..."
dotnet restore JIM.sln --verbosity quiet
print_success "NuGet packages restored"

# 3. Create .env file
print_step "Creating .env file..."

# Check if .env already exists
if [ -f .env ]; then
    print_warning ".env file already exists, skipping creation"
else
    # Check for GitHub Codespaces secrets
    if [ -n "$DOTENV_BASE64" ]; then
        # Restore from base64-encoded secret
        echo "$DOTENV_BASE64" | base64 -d > .env
        print_success ".env restored from GitHub Codespaces secret (DOTENV_BASE64)"
    else
        # Create .env with defaults and any available secrets
        cat > .env << EOF
# JIM Development Environment Configuration
# Auto-generated by .devcontainer/setup.sh

# Database Configuration (matches db.yml)
DB_NAME=jim
DB_USERNAME=jim
DB_PASSWORD=${DB_PASSWORD:-password}
DB_LOG_SENSITIVE_INFO=${DB_LOG_SENSITIVE_INFO:-false}

# SSO/OIDC Configuration
# IMPORTANT: These are development defaults. For real SSO, set GitHub Codespaces secrets.
SSO_AUTHORITY=${SSO_AUTHORITY:-https://login.microsoftonline.com/your-tenant-id/v2.0}
SSO_CLIENT_ID=${SSO_CLIENT_ID:-jim-dev-client-id}
SSO_SECRET=${SSO_SECRET:-dev-secret-change-me}
SSO_UNIQUE_IDENTIFIER_CLAIM_TYPE=${SSO_UNIQUE_IDENTIFIER_CLAIM_TYPE:-preferred_username}
SSO_UNIQUE_IDENTIFIER_METAVERSE_ATTRIBUTE_NAME=${SSO_UNIQUE_IDENTIFIER_METAVERSE_ATTRIBUTE_NAME:-userPrincipalName}
SSO_UNIQUE_IDENTIFIER_INITIAL_ADMIN_CLAIM_VALUE=${SSO_UNIQUE_IDENTIFIER_INITIAL_ADMIN_CLAIM_VALUE:-admin@example.com}

# Logging
LOGGING_LEVEL=${LOGGING_LEVEL:-Information}
LOGGING_PATH=${LOGGING_PATH:-/var/log/jim}
ENABLE_REQUEST_LOGGING=${ENABLE_REQUEST_LOGGING:-true}
EOF
        print_success ".env created with development defaults"
        print_warning "Remember to update SSO settings for real authentication!"
    fi
fi

# 4. Wait for PostgreSQL to be ready
print_step "Waiting for PostgreSQL database to be ready..."
MAX_RETRIES=30
RETRY_COUNT=0
until docker compose -f db.yml exec -T jim.database pg_isready -U jim > /dev/null 2>&1 || [ $RETRY_COUNT -eq $MAX_RETRIES ]; do
    RETRY_COUNT=$((RETRY_COUNT+1))
    echo -n "."
    sleep 1
done
echo ""

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    print_warning "PostgreSQL didn't start in time, you may need to start it manually: docker compose -f db.yml up -d"
else
    print_success "PostgreSQL is ready"
fi

# 5. Apply Entity Framework migrations
print_step "Applying Entity Framework migrations..."
if [ $RETRY_COUNT -ne $MAX_RETRIES ]; then
    # Set connection string for migrations
    export ConnectionStrings__DefaultConnection="Host=localhost;Database=jim;Username=jim;Password=${DB_PASSWORD:-password}"

    if dotnet ef database update --project JIM.PostgresData --no-build 2>/dev/null; then
        print_success "Database migrations applied successfully"
    else
        print_warning "Could not apply migrations (database might not be ready). Run manually: dotnet ef database update --project JIM.PostgresData"
    fi
else
    print_warning "Skipping migrations (database not ready)"
fi

# 6. Build the solution
print_step "Building JIM solution..."
if dotnet build JIM.sln --verbosity quiet --no-restore; then
    print_success "Solution built successfully"
else
    print_warning "Build had warnings or errors. Run 'dotnet build JIM.sln' to see details."
fi

# 7. Create useful shell aliases
print_step "Creating shell aliases..."
cat >> ~/.zshrc << 'EOF'

# JIM Development Aliases
alias jim-build='dotnet build JIM.sln'
alias jim-test='dotnet test JIM.sln'
alias jim-clean='dotnet clean JIM.sln && dotnet build JIM.sln'
alias jim-web='dotnet run --project JIM.Web'
alias jim-api='dotnet run --project JIM.Api'
alias jim-worker='dotnet run --project JIM.Worker'
alias jim-migrate='dotnet ef database update --project JIM.PostgresData'
alias jim-migration='dotnet ef migrations add --project JIM.PostgresData'
alias jim-db='docker compose -f db.yml up -d'
alias jim-db-stop='docker compose -f db.yml down'
alias jim-db-logs='docker compose -f db.yml logs -f'
alias jim-adminer='echo "Adminer running at http://localhost:8080"'
alias jim-stack='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml up -d'
alias jim-stack-build='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml up -d --build'
alias jim-stack-logs='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml logs -f'
alias jim-stack-down='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml down'
EOF

print_success "Shell aliases created (restart terminal or run: source ~/.zshrc)"

# 8. Display useful information
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✓ JIM Development Environment Ready!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Quick Start Commands:"
echo "  jim-build          → Build the entire solution"
echo "  jim-test           → Run all tests"
echo "  jim-web            → Run the Blazor web application (local, debuggable)"
echo "  jim-api            → Run the API (local, debuggable)"
echo "  jim-db             → Start PostgreSQL database only"
echo ""
echo "🐳 Docker Stack Commands:"
echo "  jim-stack          → Start full Docker stack (all services)"
echo "  jim-stack-build    → Build and start Docker stack"
echo "  jim-stack-logs     → View Docker stack logs"
echo "  jim-stack-down     → Stop Docker stack"
echo ""
echo "🔧 Database Commands:"
echo "  jim-migrate        → Apply pending migrations"
echo "  jim-migration [N]  → Create a new migration"
echo "  jim-db-logs        → View database logs"
echo "  jim-adminer        → Get Adminer URL"
echo ""
echo "🌐 Available Services:"
echo "  PostgreSQL:        localhost:5432"
echo "  Adminer:           http://localhost:8080"
echo ""
echo "  When running locally (F5):"
echo "    JIM Web:         https://localhost:7000"
echo "    JIM API:         https://localhost:7203"
echo ""
echo "  When running Docker stack:"
echo "    JIM Web:         http://localhost:5200"
echo "    JIM API:         http://localhost:5202"
echo ""
echo "📖 Documentation:"
echo "  Developer Guide:   docs/DEVELOPER_GUIDE.md"
echo "  Quick Reference:   CLAUDE.md"
echo ""
echo "🚀 To start developing (choose one):"
echo ""
echo "  Option 1 - Local Debug (Recommended):"
echo "    1. Press F5 in VS Code"
echo "    2. Select 'JIM Full Stack' or 'JIM Web Stack'"
echo "    3. Set breakpoints and debug"
echo ""
echo "  Option 2 - Docker Stack:"
echo "    1. Review .env file and update SSO settings"
echo "    2. Run: jim-stack"
echo "    3. Open: http://localhost:5200"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
