#!/bin/bash
set -e

echo "🚀 Setting up JIM development environment..."
echo ""

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_step() {
    echo -e "${BLUE}▶${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# 1. Install .NET EF Core tools
print_step "Installing .NET Entity Framework Core tools..."
# Clean up any corrupted tool state first, then install fresh
# This handles cases where the tool cache becomes corrupted after container rebuilds
rm -rf ~/.dotnet/tools/dotnet-ef ~/.dotnet/tools/.store/dotnet-ef 2>/dev/null || true
# Use explicit version to avoid "Settings file not found" errors with latest package
if dotnet tool install --global dotnet-ef --version 9.0.0; then
    print_success "dotnet-ef 9.0.0 installed globally"
else
    print_warning "dotnet-ef installation failed - you may need to install manually: dotnet tool install --global dotnet-ef --version 9.0.0"
fi

# Add .NET tools to PATH
export PATH="$PATH:$HOME/.dotnet/tools"
echo 'export PATH="$PATH:$HOME/.dotnet/tools"' >> ~/.zshrc
echo 'export PATH="$PATH:$HOME/.dotnet/tools"' >> ~/.bashrc

# 2. Restore NuGet packages
print_step "Restoring NuGet packages..."
dotnet restore JIM.sln --verbosity quiet
print_success "NuGet packages restored"

# 3. Create .env file
print_step "Creating .env file..."

# Check if .env already exists
if [ -f .env ]; then
    print_warning ".env file already exists, skipping creation"
else
    # Check for GitHub Codespaces secrets
    if [ -n "$DOTENV_BASE64" ]; then
        # Restore from base64-encoded secret
        echo "$DOTENV_BASE64" | base64 -d > .env
        print_success ".env restored from GitHub Codespaces secret (DOTENV_BASE64)"
    else
        # Create .env with defaults and any available secrets
        cat > .env << EOF
# JIM Development Environment Configuration
# Auto-generated by .devcontainer/setup.sh

# Database Configuration (matches db.yml)
JIM_DB_NAME=jim
JIM_DB_USERNAME=jim
JIM_DB_PASSWORD=${JIM_DB_PASSWORD:-password}
JIM_DB_LOG_SENSITIVE_INFO=${JIM_DB_LOG_SENSITIVE_INFO:-false}

# SSO/OIDC Configuration
# IMPORTANT: These are development defaults. For real SSO, set GitHub Codespaces secrets.
JIM_SSO_AUTHORITY=${JIM_SSO_AUTHORITY:-https://login.microsoftonline.com/your-tenant-id/v2.0}
JIM_SSO_CLIENT_ID=${JIM_SSO_CLIENT_ID:-jim-dev-client-id}
JIM_SSO_SECRET=${JIM_SSO_SECRET:-dev-secret-change-me}
JIM_SSO_CLAIM_TYPE=${JIM_SSO_CLAIM_TYPE:-preferred_username}
JIM_SSO_MV_ATTRIBUTE=${JIM_SSO_MV_ATTRIBUTE:-userPrincipalName}
JIM_SSO_INITIAL_ADMIN=${JIM_SSO_INITIAL_ADMIN:-admin@example.com}

# Logging
JIM_LOG_LEVEL=${JIM_LOG_LEVEL:-Information}
JIM_LOG_PATH=${JIM_LOG_PATH:-/var/log/jim}
JIM_LOG_REQUESTS=${JIM_LOG_REQUESTS:-true}
EOF
        print_success ".env created with development defaults"
        print_warning "Remember to update SSO settings for real authentication!"
    fi
fi

# 4. Wait for PostgreSQL to be ready
print_step "Waiting for PostgreSQL database to be ready..."
MAX_RETRIES=30
RETRY_COUNT=0
until docker compose -f db.yml exec -T jim.database pg_isready -U jim > /dev/null 2>&1 || [ $RETRY_COUNT -eq $MAX_RETRIES ]; do
    RETRY_COUNT=$((RETRY_COUNT+1))
    echo -n "."
    sleep 1
done
echo ""

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    print_warning "PostgreSQL didn't start in time, you may need to start it manually: docker compose -f db.yml up -d"
else
    print_success "PostgreSQL is ready"
fi

# 5. Apply Entity Framework migrations
print_step "Applying Entity Framework migrations..."
if [ $RETRY_COUNT -ne $MAX_RETRIES ]; then
    # Set connection string for migrations
    export ConnectionStrings__DefaultConnection="Host=localhost;Database=jim;Username=jim;Password=${JIM_DB_PASSWORD:-password}"

    if dotnet ef database update --project JIM.PostgresData --no-build 2>/dev/null; then
        print_success "Database migrations applied successfully"
    else
        print_warning "Could not apply migrations (database might not be ready). Run manually: dotnet ef database update --project JIM.PostgresData"
    fi
else
    print_warning "Skipping migrations (database not ready)"
fi

# 6. Build the solution
print_step "Building JIM solution..."
if dotnet build JIM.sln --verbosity quiet --no-restore; then
    print_success "Solution built successfully"
else
    print_warning "Build had warnings or errors. Run 'dotnet build JIM.sln' to see details."
fi

# 7. Create connector-files directory with symlink to test data
print_step "Setting up connector-files directory..."
mkdir -p connector-files

# Create symlink to test/Data directory (dynamic - new files appear automatically)
if [ ! -L connector-files/test-data ]; then
    if [ -d "test/Data" ]; then
        ln -s "$(pwd)/test/Data" connector-files/test-data
        print_success "Symlink created: connector-files/test-data -> test/Data"
    else
        print_warning "test/Data directory not found, skipping symlink"
    fi
else
    print_success "Symlink already exists: connector-files/test-data"
fi

# 8. Configure Git SSH commit signing
print_step "Configuring Git SSH commit signing..."

# Check if SSH agent has keys forwarded
if ssh-add -l &>/dev/null; then
    # Get the first SSH key from the agent
    SSH_KEY=$(ssh-add -L | head -1)

    if [ -n "$SSH_KEY" ]; then
        # Configure git to use SSH signing
        git config --global gpg.format ssh
        git config --global commit.gpgsign true
        git config --global user.signingkey "key::$SSH_KEY"

        # Create allowed_signers file for local verification
        # Uses the git user email (if configured) or a placeholder
        GIT_EMAIL=$(git config --global user.email || echo "developer@local")
        mkdir -p ~/.ssh
        echo "$GIT_EMAIL $SSH_KEY" > ~/.ssh/allowed_signers
        git config --global gpg.ssh.allowedSignersFile ~/.ssh/allowed_signers

        print_success "Git SSH signing configured (key from SSH agent)"
    else
        print_warning "SSH agent has no keys - commit signing not configured"
    fi
else
    print_warning "SSH agent not available - commit signing not configured"
    print_warning "To enable signing, ensure SSH agent forwarding is working"
fi

# 9. Create useful shell aliases
print_step "Creating shell aliases..."
cat >> ~/.zshrc << 'EOF'

# JIM Development Aliases
# Unset GITHUB_TOKEN to allow gh CLI to use its own authentication with project scopes
unset GITHUB_TOKEN

alias jim-build='dotnet build JIM.sln'
alias jim-test='dotnet test JIM.sln'
alias jim-clean='dotnet clean JIM.sln && dotnet build JIM.sln'
alias jim-web='dotnet run --project JIM.Web'
alias jim-api='dotnet run --project JIM.Api'
alias jim-worker='dotnet run --project JIM.Worker'
alias jim-migrate='dotnet ef database update --project JIM.PostgresData'
alias jim-migration='dotnet ef migrations add --project JIM.PostgresData'
alias jim-db='docker compose -f db.yml up -d'
alias jim-db-stop='docker compose -f db.yml down'
alias jim-db-logs='docker compose -f db.yml logs -f'
alias jim-adminer='echo "Adminer running at http://localhost:8080"'
alias jim-stack='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml --profile with-db up -d'
alias jim-stack-build='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml --profile with-db up -d --build'
alias jim-stack-logs='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml --profile with-db logs -f'
alias jim-stack-down='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml --profile with-db down'
alias jim-web-build='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml --profile with-db up -d --build jim.web'
alias jim-worker-build='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml --profile with-db up -d --build jim.worker'
alias jim-scheduler-build='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml --profile with-db up -d --build jim.scheduler'
alias jim-reset='docker compose -f docker-compose.yml -f docker-compose.override.codespaces.yml --profile with-db down && docker volume rm -f jim-db-volume jim-logs-volume && echo "JIM reset complete. Run jim-stack-build to start fresh."'
EOF

print_success "Shell aliases created (restart terminal or run: source ~/.zshrc)"

# 10. Display useful information
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✓ JIM Development Environment Ready!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Quick Start Commands:"
echo "  jim-build          → Build the entire solution"
echo "  jim-test           → Run all tests"
echo "  jim-web            → Run the Blazor web application (local, debuggable)"
echo "  jim-api            → Run the API (local, debuggable)"
echo "  jim-db             → Start PostgreSQL database only"
echo ""
echo "🐳 Docker Stack Commands:"
echo "  jim-stack          → Start full Docker stack (all services)"
echo "  jim-stack-build    → Build and start Docker stack"
echo "  jim-stack-logs     → View Docker stack logs"
echo "  jim-stack-down     → Stop Docker stack"
echo "  jim-web-build      → Quick rebuild just jim.web container"
echo "  jim-worker-build   → Quick rebuild just jim.worker container"
echo "  jim-reset          → Reset JIM (delete database & logs volumes)"
echo ""
echo "🔧 Database Commands:"
echo "  jim-migrate        → Apply pending migrations"
echo "  jim-migration [N]  → Create a new migration"
echo "  jim-db-logs        → View database logs"
echo "  jim-adminer        → Get Adminer URL"
echo ""
echo "🌐 Available Services:"
echo "  PostgreSQL:        localhost:5432"
echo "  Adminer:           http://localhost:8080"
echo ""
echo "  When running locally (F5):"
echo "    JIM Web:         https://localhost:7000"
echo "    JIM API:         https://localhost:7203"
echo ""
echo "  When running Docker stack:"
echo "    JIM Web:         http://localhost:5200"
echo "    JIM API:         http://localhost:5202"
echo ""
echo "📖 Documentation:"
echo "  Developer Guide:   docs/DEVELOPER_GUIDE.md"
echo "  Quick Reference:   CLAUDE.md"
echo ""
echo "🚀 To start developing (choose one):"
echo ""
echo "  Option 1 - Local Debug (Recommended):"
echo "    1. Press F5 in VS Code"
echo "    2. Select 'JIM Full Stack' or 'JIM Web Stack'"
echo "    3. Set breakpoints and debug"
echo ""
echo "  Option 2 - Docker Stack:"
echo "    1. Review .env file and update SSO settings"
echo "    2. Run: jim-stack"
echo "    3. Open: http://localhost:5200"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
