// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

using JIM.TestSupport;
using Npgsql;

namespace JIM.Worker.Tests.Support;

/// <summary>
/// Pins <see cref="PostgresTestDatabase.ResetAsync"/>, the between-tests reset every <c>RequiresPostgres</c> fixture
/// runs in its <c>[SetUp]</c>: every table in <c>public</c> emptied and its identity restarted, the migration
/// history kept, and nothing outside <c>public</c> touched.
/// </summary>
/// <remarks>
/// Runs against its own scratch database with a small hand-made schema rather than the shared migrated one, so the
/// cases it needs (quoted and unquoted names, a foreign key, an empty schema, a second schema) do not depend on
/// JIM's model. Opt-in via the same <c>JIM_TEST_RESET_*</c> variables as the rest of the tier; the role needs
/// <c>CREATEDB</c> (CI's postgres superuser has it).
/// </remarks>
[TestFixture]
[Category("RequiresPostgres")]
public class PostgresTestDatabaseResetTests
{
    private const string ScratchDatabaseName = "jim_reset_helper_test";

    private string _adminConnectionString = null!;
    private string _scratchConnectionString = null!;

    [OneTimeSetUp]
    public async Task OneTimeSetUpAsync()
    {
        var dbName = Environment.GetEnvironmentVariable("JIM_TEST_RESET_DB");
        if (string.IsNullOrEmpty(dbName))
            Assert.Ignore("JIM_TEST_RESET_DB not set; skipping real-PostgreSQL reset helper tests.");

        var host = Environment.GetEnvironmentVariable("JIM_TEST_RESET_HOST") ?? "localhost";
        var user = Environment.GetEnvironmentVariable("JIM_TEST_RESET_USER") ?? "postgres";
        var pass = Environment.GetEnvironmentVariable("JIM_TEST_RESET_PASSWORD") ?? "postgres";
        var port = Environment.GetEnvironmentVariable("JIM_TEST_RESET_PORT") ?? "5432";

        _adminConnectionString = $"Host={host};Port={port};Database={dbName};Username={user};Password={pass}";
        _scratchConnectionString = $"Host={host};Port={port};Database={ScratchDatabaseName};Username={user};Password={pass}";

        // WITH (FORCE) terminates any connection a previous aborted run left behind.
        await PostgresTestDatabase.ExecuteDatabaseCreateDropAsync(_adminConnectionString, $"DROP DATABASE IF EXISTS {ScratchDatabaseName} WITH (FORCE)");
        await PostgresTestDatabase.ExecuteDatabaseCreateDropAsync(_adminConnectionString, $"CREATE DATABASE {ScratchDatabaseName}");
    }

    [OneTimeTearDown]
    public async Task OneTimeTearDownAsync()
    {
        if (_adminConnectionString != null)
            await PostgresTestDatabase.ExecuteDatabaseCreateDropAsync(_adminConnectionString, $"DROP DATABASE IF EXISTS {ScratchDatabaseName} WITH (FORCE)");
    }

    [SetUp]
    public async Task SetUpAsync()
    {
        // A mixed-case table needs quoting and a lower-case one does not; the child's foreign key means the reset
        // has to empty both in one go or be refused.
        await ExecuteAsync(_scratchConnectionString, $"""
            DROP SCHEMA IF EXISTS public CASCADE;
            DROP SCHEMA IF EXISTS other CASCADE;
            CREATE SCHEMA public;
            CREATE SCHEMA other;
            CREATE TABLE public."{PostgresTestDatabase.MigrationHistoryTable}" ("MigrationId" text PRIMARY KEY);
            CREATE TABLE public."Parents" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" text);
            CREATE TABLE public."Children" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ParentId" integer NOT NULL REFERENCES public."Parents" ("Id"));
            CREATE TABLE public.settings (key text PRIMARY KEY);
            CREATE TABLE other."Things" ("Id" integer PRIMARY KEY);

            INSERT INTO public."{PostgresTestDatabase.MigrationHistoryTable}" VALUES ('20260101000000_Initial');
            INSERT INTO public."Parents" ("Name") VALUES ('a'), ('b'), ('c');
            INSERT INTO public."Children" ("ParentId") VALUES (1), (2);
            INSERT INTO public.settings VALUES ('one');
            INSERT INTO other."Things" VALUES (1);
            """);
    }

    [Test]
    public async Task ResetAsync_TablesHoldRows_EmptiesEveryPublicTableAsync()
    {
        await PostgresTestDatabase.ResetAsync(_scratchConnectionString);

        Assert.That(await CountAsync("public", "Parents"), Is.Zero);
        Assert.That(await CountAsync("public", "Children"), Is.Zero);
        Assert.That(await CountAsync("public", "settings"), Is.Zero);
    }

    [Test]
    public async Task ResetAsync_MigrationHistoryHoldsRows_KeepsThemAsync()
    {
        await PostgresTestDatabase.ResetAsync(_scratchConnectionString);

        Assert.That(await CountAsync("public", PostgresTestDatabase.MigrationHistoryTable), Is.EqualTo(1));
    }

    [Test]
    public async Task ResetAsync_IdentityHasAdvanced_RestartsItAsync()
    {
        await PostgresTestDatabase.ResetAsync(_scratchConnectionString);

        await using var connection = new NpgsqlConnection(_scratchConnectionString);
        await connection.OpenAsync();
        await using var insert = new NpgsqlCommand("""INSERT INTO public."Parents" ("Name") VALUES ('d') RETURNING "Id" """, connection);
        Assert.That(await insert.ExecuteScalarAsync(), Is.EqualTo(1));
    }

    [Test]
    public async Task ResetAsync_TableInAnotherSchema_LeavesItAloneAsync()
    {
        await PostgresTestDatabase.ResetAsync(_scratchConnectionString);

        Assert.That(await CountAsync("other", "Things"), Is.EqualTo(1));
    }

    [Test]
    public async Task ResetAsync_OnlyTheMigrationHistoryExists_DoesNothingAsync()
    {
        await ExecuteAsync(_scratchConnectionString, """
            DROP TABLE public."Children";
            DROP TABLE public."Parents";
            DROP TABLE public.settings;
            """);

        Assert.DoesNotThrowAsync(() => PostgresTestDatabase.ResetAsync(_scratchConnectionString));
        Assert.That(await CountAsync("public", PostgresTestDatabase.MigrationHistoryTable), Is.EqualTo(1));
    }

    private async Task<long> CountAsync(string schema, string table)
    {
        await using var connection = new NpgsqlConnection(_scratchConnectionString);
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand($"SELECT count(*) FROM \"{schema}\".\"{table}\"", connection);
        return (long)(await command.ExecuteScalarAsync())!;
    }

    private static async Task ExecuteAsync(string connectionString, string sql)
    {
        await using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync();
    }
}
