# Copyright (c) Tetron Limited. All rights reserved.
# Licensed under the Tetron Commercial License. See LICENSE file in the project root.

<#
.SYNOPSIS
    Exports self-contained light/dark SVG variants of selected concept diagrams for the GitHub README.

.DESCRIPTION
    The hand-authored diagrams under docs/assets/diagrams/ carry no colours of their own; they are
    themed by the .jimdg-* classes in docs/assets/stylesheets/custom.css when inlined into the docs
    site. GitHub cannot apply that stylesheet, so this script bakes the styling into standalone
    copies: for each source diagram it resolves the --jimdg-* tokens for each theme and injects a
    <style> element, writing the results to .github/diagrams/<name>-light.svg and -dark.svg for the
    README's <picture> embeds.

    Run it after changing an exported diagram (or the diagram tokens in custom.css) and commit the
    regenerated files alongside the source.

.EXAMPLE
    pwsh ./scripts/Export-ReadmeDiagrams.ps1
#>
[CmdletBinding()]
param(
    # Diagram basenames (without .svg) under docs/assets/diagrams/ to export.
    [string[]]$Diagrams = @('system-context', 'containers'),

    # Output directory for the baked SVGs, relative to the repository root.
    [string]$OutputDirectory = '.github/diagrams'
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$cssPath = Join-Path $repoRoot 'docs/assets/stylesheets/custom.css'
$diagramDir = Join-Path $repoRoot 'docs/assets/diagrams'
$outDir = Join-Path $repoRoot $OutputDirectory

$css = Get-Content -Path $cssPath -Raw

# Collect the --jimdg-* token declarations for a colour scheme from every standalone
# [data-md-color-scheme="<scheme>"] { ... } block in custom.css. Compound selectors
# (e.g. scheme-prefixed component rules) never match because the pattern requires the
# opening brace to follow the scheme selector directly.
function Get-SchemeToken([string]$Scheme) {
    $tokens = [System.Collections.Generic.List[string]]::new()
    $blockPattern = "(?s)\[data-md-color-scheme=""$Scheme""\]\s*\{(.*?)\}"
    foreach ($block in [regex]::Matches($css, $blockPattern)) {
        foreach ($declaration in [regex]::Matches($block.Groups[1].Value, '--jimdg-[a-z-]+\s*:\s*[^;]+;')) {
            $tokens.Add($declaration.Value.Trim())
        }
    }
    if ($tokens.Count -eq 0) { throw "No --jimdg-* tokens found for scheme '$Scheme' in $cssPath" }
    return $tokens
}

# Collect every top-level .jim-diagram rule block (the shared shape and text styling).
# Indented occurrences (inside @media blocks) are deliberately excluded; the
# reduced-motion rule is re-added verbatim below.
$ruleMatches = [regex]::Matches($css, '(?ms)^\.jim-diagram[^{]*?\{.*?\}')
if ($ruleMatches.Count -eq 0) { throw "No .jim-diagram rules found in $cssPath" }
$rules = ($ruleMatches | ForEach-Object { $_.Value }) -join "`n"

$null = New-Item -ItemType Directory -Path $outDir -Force
# Anchored to line start: the header comments mention "<svg>" in prose, and an
# unanchored match would inject the style block into the middle of a comment.
$svgTagPattern = [regex]'(?m)^<svg\b[^>]*>'

foreach ($name in $Diagrams) {
    $sourcePath = Join-Path $diagramDir "$name.svg"
    if (-not (Test-Path $sourcePath)) { throw "Source diagram not found: $sourcePath" }
    $svg = Get-Content -Path $sourcePath -Raw

    foreach ($theme in @(
            @{ Scheme = 'default'; Suffix = 'light' },
            @{ Scheme = 'slate'; Suffix = 'dark' }
        )) {
        $tokens = (Get-SchemeToken -Scheme $theme.Scheme) -join "`n  "
        $style = @"
<style>
:root {
  $tokens
}
svg { font-family: "IBM Plex Sans", -apple-system, "Segoe UI", sans-serif; }
$rules
@media (prefers-reduced-motion: reduce) { .jimdg-packet { display: none; } }
</style>
"@
        $baked = $svgTagPattern.Replace($svg, ('$0' + "`n" + $style), 1)
        $header = "<!-- Generated by scripts/Export-ReadmeDiagrams.ps1 from docs/assets/diagrams/$name.svg - do not edit by hand. -->`n"
        $outPath = Join-Path $outDir "$name-$($theme.Suffix).svg"
        Set-Content -Path $outPath -Value ($header + $baked) -NoNewline
        Write-Host "Exported $outPath"
    }
}
