// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

namespace JIM.Models.Transactional.DTOs;

/// <summary>
/// Which generated value decisions a read or an action applies to (Unique Value Generation, #242, release 4, Phase 9):
/// the Generated Values tab, its REST and PowerShell counterparts, and the bulk "Try again" over them. One type serves
/// the list and the action deliberately, as <see cref="PendingPasswordChangeFilter"/> does for the password queue: "try
/// again for everything shown" is the filter the administrator is looking at, not the page of rows they have scrolled to.
/// Every member narrows; an empty filter means every decision.
/// </summary>
public class GeneratedValueDecisionFilter
{
    /// <summary>
    /// Restrict to decisions involving one Connected System: the system that rejected the value, the system whose
    /// account anchors it, or any system the generated value is exported to and checked in (its participating targets).
    /// </summary>
    public int? ConnectedSystemId { get; set; }

    /// <summary>
    /// Restrict to values generated by Attribute Flows on one Synchronisation Rule.
    /// </summary>
    public int? SyncRuleId { get; set; }

    /// <summary>
    /// Restrict to one status. Null means both statuses a list shows (<see cref="GeneratedValueDecisionStatus.NeedsDecision"/>
    /// and <see cref="GeneratedValueDecisionStatus.RenameAllowed"/>); <see cref="GeneratedValueDecisionStatus.Released"/>
    /// matches nothing in a list.
    /// </summary>
    public GeneratedValueDecisionStatus? Status { get; set; }

    /// <summary>
    /// Restrict to one Metaverse Object's values (import mode), for its banner; an export-mode value matches when its
    /// Connected System Object is joined to this Metaverse Object.
    /// </summary>
    public Guid? MetaverseObjectId { get; set; }

    /// <summary>
    /// Restrict to these generated values, by assignment id: a row action or a selection. Combines with the other
    /// members rather than replacing them, so "these, if they still need a decision" is expressible.
    /// </summary>
    public IReadOnlyCollection<Guid>? Ids { get; set; }

    /// <summary>
    /// Whether the filter narrows the set at all. A bulk action refuses an empty filter unless the caller says it means
    /// every decision, so a forgotten parameter never acts on everything.
    /// </summary>
    public bool HasCriteria => ConnectedSystemId.HasValue || SyncRuleId.HasValue || MetaverseObjectId.HasValue || Ids is { Count: > 0 };
}
