#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Analyses PostgreSQL query performance using pg_stat_statements.

.DESCRIPTION
    Captures and analyses query execution statistics from pg_stat_statements.
    Can optionally run an integration test first to generate a fresh workload,
    or analyse existing stats from a previous run.

    Requires pg_stat_statements to be enabled in PostgreSQL
    (shared_preload_libraries=pg_stat_statements).

.PARAMETER Scenario
    The integration test scenario to run. Default: Scenario8-CrossDomainEntitlementSync

.PARAMETER Template
    The test data template size. Default: Medium

.PARAMETER DirectoryType
    The directory type for the integration test. Default: OpenLDAP

.PARAMETER TopN
    Number of top queries to display (by total execution time). Default: 20

.PARAMETER SkipTest
    Skip running the integration test and analyse existing pg_stat_statements data.

.PARAMETER ResetOnly
    Reset pg_stat_statements counters and exit. Useful for manual test workflows.

.PARAMETER OutputFile
    Custom output file path. Default: test/integration/results/query-analysis/<timestamp>.md

.EXAMPLE
    ./Analyse-QueryPerformance.ps1
    Resets stats, runs S8 OpenLDAP Medium, captures and displays query analysis.

.EXAMPLE
    ./Analyse-QueryPerformance.ps1 -SkipTest
    Analyses existing pg_stat_statements data without running a test.

.EXAMPLE
    ./Analyse-QueryPerformance.ps1 -Template Small -TopN 30
    Runs S8 OpenLDAP Small and shows top 30 queries.

.EXAMPLE
    ./Analyse-QueryPerformance.ps1 -ResetOnly
    Resets pg_stat_statements counters and exits.
#>

param(
    [string]$Scenario = "Scenario8-CrossDomainEntitlementSync",

    [ValidateSet("Nano", "Micro", "Small", "Medium", "MediumLarge", "Large", "XLarge", "XXLarge")]
    [string]$Template = "Medium",

    [ValidateSet("SambaAD", "OpenLDAP")]
    [string]$DirectoryType = "OpenLDAP",

    [int]$TopN = 20,

    [switch]$SkipTest,

    [switch]$ResetOnly,

    [string]$OutputFile
)

# ============================================================================
# Colours
# ============================================================================

$RED = "`e[31m"
$GREEN = "`e[32m"
$YELLOW = "`e[33m"
$CYAN = "`e[36m"
$GRAY = "`e[90m"
$BOLD = "`e[1m"
$NC = "`e[0m"

# ============================================================================
# Configuration
# ============================================================================

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent (Split-Path -Parent $scriptRoot)
$composeFiles = @("-f", "docker-compose.yml", "-f", "docker-compose.override.yml")

# Include local override if it exists (generated by postgres-tune.sh)
$localOverride = Join-Path $repoRoot "docker-compose.local.yml"
if (Test-Path $localOverride) {
    $composeFiles += @("-f", "docker-compose.local.yml")
}

# Field delimiter — chosen to avoid clashes with SQL text
$DELIM = "|||"

# ============================================================================
# Helper functions
# ============================================================================

function Invoke-Psql {
    param(
        [string]$Sql,
        [switch]$TuplesOnly,
        [switch]$Csv
    )

    $flags = @()
    if ($TuplesOnly) { $flags += "-t" }
    if ($Csv) { $flags += "--csv" }
    $flags += @("-U", "jim", "-d", "jim", "-c", $Sql)

    $result = docker compose @composeFiles exec -T jim.database psql @flags 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "${RED}psql error: $result${NC}"
        return $null
    }
    return $result
}

function Invoke-PsqlDelimited {
    <#
    .SYNOPSIS
        Runs a SQL query and returns results using a custom field delimiter,
        avoiding CSV multi-line quoting issues with SQL query text.
    #>
    param([string]$Sql)

    $flags = @("-t", "-A", "-F", $DELIM, "-U", "jim", "-d", "jim", "-c", $Sql)
    $result = docker compose @composeFiles exec -T jim.database psql @flags 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "${RED}psql error: $result${NC}"
        return $null
    }
    return $result
}

function Format-FriendlyTime {
    param([double]$Ms)

    if ($Ms -lt 1) {
        return "$($Ms.ToString('F3'))ms"
    }
    elseif ($Ms -lt 1000) {
        return "$($Ms.ToString('F1'))ms"
    }
    elseif ($Ms -lt 60000) {
        $secs = $Ms / 1000
        return "$($secs.ToString('F1'))s"
    }
    else {
        $totalSecs = [int]($Ms / 1000)
        $mins = [Math]::Floor($totalSecs / 60)
        $secs = $totalSecs % 60
        if ($secs -eq 0) { return "${mins}m" }
        return "${mins}m ${secs}s"
    }
}

function Get-TimeColour {
    param([double]$MeanMs)

    if ($MeanMs -ge 100) { return $RED }
    elseif ($MeanMs -ge 10) { return $YELLOW }
    else { return $GREEN }
}

# ============================================================================
# Banner
# ============================================================================

Write-Host ""
Write-Host "${BOLD}${CYAN}PostgreSQL Query Performance Analysis${NC}"
Write-Host "${GRAY}Using pg_stat_statements${NC}"
Write-Host ""

# ============================================================================
# Ensure pg_stat_statements extension exists and is queryable
# ============================================================================

function Initialize-PgStatStatements {
    <#
    .SYNOPSIS
        Creates the pg_stat_statements extension if it doesn't exist.
        The shared library is loaded at PostgreSQL startup (shared_preload_libraries),
        but the SQL views/functions require CREATE EXTENSION.
    #>

    # Check database container is running
    $dbCheck = docker compose @composeFiles ps --status running --format "{{.Name}}" 2>&1 | Where-Object { $_ -match "database" }
    if (-not $dbCheck) {
        Write-Host "${RED}Error: jim.database container is not running.${NC}"
        Write-Host "Start it with: ${CYAN}jim-db${NC} or ${CYAN}jim-stack${NC}"
        return $false
    }

    # Try to query — if it works, extension already exists
    $extCheck = Invoke-Psql -Sql "SELECT 1 FROM pg_stat_statements LIMIT 0" -TuplesOnly 2>$null
    if ($null -ne $extCheck -and $LASTEXITCODE -eq 0) {
        return $true
    }

    # Create extension
    Write-Host "${YELLOW}pg_stat_statements extension not found. Creating...${NC}"
    $createResult = Invoke-Psql -Sql "CREATE EXTENSION IF NOT EXISTS pg_stat_statements"
    if ($null -eq $createResult -or $LASTEXITCODE -ne 0) {
        Write-Host "${RED}Error: Could not create pg_stat_statements extension.${NC}"
        Write-Host "Ensure shared_preload_libraries=pg_stat_statements is set in the PostgreSQL command."
        Write-Host "After adding it, restart the database container."
        return $false
    }
    Write-Host "${GREEN}Extension created successfully.${NC}"
    return $true
}

# ============================================================================
# ResetOnly mode — reset stats and exit
# ============================================================================

if ($ResetOnly) {
    if (-not (Initialize-PgStatStatements)) { exit 1 }
    Write-Host "${CYAN}Resetting pg_stat_statements counters...${NC}"
    Invoke-Psql -Sql "SELECT pg_stat_statements_reset()" -TuplesOnly | Out-Null
    Write-Host "${GREEN}Stats reset. Exiting.${NC}"
    exit 0
}

# ============================================================================
# Run integration test (unless -SkipTest)
# ============================================================================
# When running a test, the test runner recreates the database from scratch
# (volumes are deleted). pg_stat_statements shared library is still loaded
# (it's in shared_preload_libraries), so stats are collected in shared memory,
# but the SQL extension must be (re-)created after the test to query them.
# ============================================================================

if (-not $SkipTest) {
    Write-Host "${BOLD}Running integration test: ${Scenario} / ${Template} / ${DirectoryType}${NC}"
    Write-Host "${GRAY}This will take several minutes...${NC}"
    Write-Host ""

    $testRunner = Join-Path $scriptRoot "Run-IntegrationTests.ps1"
    & $testRunner -Scenario $Scenario -Template $Template -DirectoryType $DirectoryType

    if ($LASTEXITCODE -ne 0) {
        Write-Host ""
        Write-Host "${YELLOW}Warning: Integration test exited with code $LASTEXITCODE${NC}"
        Write-Host "Proceeding with query analysis anyway (partial data may still be useful)."
    }

    Write-Host ""
    Write-Host "${CYAN}Integration test complete. Capturing query statistics...${NC}"
    Write-Host ""
}

# Ensure extension exists (may need creating after test runner recreated the database)
if (-not (Initialize-PgStatStatements)) { exit 1 }

# If not running a test, stats are already accumulated from previous activity
# If running a test, the test runner started fresh (volume wipe) so stats are from that run only

# ============================================================================
# Query pg_stat_statements
# ============================================================================

# Use regexp_replace to collapse newlines in query text, and a custom delimiter
# to avoid CSV quoting issues with SQL that contains commas.
$statsSql = @"
SELECT
    queryid::text,
    regexp_replace(LEFT(query, 300), E'[\\n\\r\\t]+', ' ', 'g'),
    calls::text,
    ROUND(total_exec_time::numeric, 2)::text,
    ROUND(mean_exec_time::numeric, 2)::text,
    ROUND(min_exec_time::numeric, 2)::text,
    ROUND(max_exec_time::numeric, 2)::text,
    ROUND(stddev_exec_time::numeric, 2)::text,
    rows::text,
    shared_blks_hit::text,
    shared_blks_read::text,
    CASE WHEN shared_blks_hit + shared_blks_read > 0
        THEN ROUND((shared_blks_hit::numeric / (shared_blks_hit + shared_blks_read)) * 100, 1)::text
        ELSE '100'
    END
FROM pg_stat_statements
WHERE dbid = (SELECT oid FROM pg_database WHERE datname = 'jim')
ORDER BY total_exec_time DESC
LIMIT $TopN
"@

$rawData = Invoke-PsqlDelimited -Sql $statsSql
if ($null -eq $rawData) {
    Write-Host "${RED}Error: Failed to query pg_stat_statements.${NC}"
    exit 1
}

# Parse delimited output (one line per row, fields separated by $DELIM)
$lines = ($rawData -join "`n") -split "`n" | Where-Object { $_.Trim() -ne "" }

$queries = @()
foreach ($line in $lines) {
    $fields = $line -split [regex]::Escape($DELIM)
    if ($fields.Count -lt 12) { continue }

    $queries += [PSCustomObject]@{
        QueryId      = $fields[0].Trim()
        QueryPreview = $fields[1].Trim()
        Calls        = [long]$fields[2].Trim()
        TotalMs      = [double]$fields[3].Trim()
        MeanMs       = [double]$fields[4].Trim()
        MinMs        = [double]$fields[5].Trim()
        MaxMs        = [double]$fields[6].Trim()
        StdDevMs     = [double]$fields[7].Trim()
        Rows         = [long]$fields[8].Trim()
        BlksHit      = [long]$fields[9].Trim()
        BlksRead     = [long]$fields[10].Trim()
        CacheHitPct  = [double]$fields[11].Trim()
    }
}

if ($queries.Count -eq 0) {
    Write-Host "${YELLOW}No queries found for the 'jim' database.${NC}"
    exit 0
}

# ============================================================================
# Display results
# ============================================================================

$totalTime = ($queries | Measure-Object -Property TotalMs -Sum).Sum
$totalCalls = ($queries | Measure-Object -Property Calls -Sum).Sum

Write-Host ""
Write-Host "${BOLD}${CYAN}=== Query Performance Summary ===${NC}"
Write-Host ""
Write-Host "  Top ${TopN} queries by total execution time"
Write-Host "  Total DB time (top ${TopN}): ${BOLD}$(Format-FriendlyTime $totalTime)${NC} across ${BOLD}$($totalCalls.ToString('N0'))${NC} calls"
Write-Host ""

# Column headers
$rankW = 4
$callsW = 8
$totalW = 10
$meanW = 10
$maxW = 10
$rowsW = 10
$cacheW = 7
$queryW = 80

$headerLine = "{0,$rankW} {1,$callsW} {2,$totalW} {3,$meanW} {4,$maxW} {5,$rowsW} {6,$cacheW}  {7}" -f "#", "Calls", "Total", "Mean", "Max", "Rows", "Cache%", "Query"
Write-Host "${BOLD}${headerLine}${NC}"
Write-Host ("{0}" -f ("-" * ($rankW + $callsW + $totalW + $meanW + $maxW + $rowsW + $cacheW + $queryW + 8)))

$rank = 0
foreach ($q in $queries) {
    $rank++
    $colour = Get-TimeColour -MeanMs $q.MeanMs

    # Truncate query for display
    $queryDisplay = $q.QueryPreview -replace '\s+', ' '
    if ($queryDisplay.Length -gt $queryW) {
        $queryDisplay = $queryDisplay.Substring(0, $queryW - 3) + "..."
    }

    $line = "{0,$rankW} {1,$callsW} {2,$totalW} {3,$meanW} {4,$maxW} {5,$rowsW} {6,$cacheW}  {7}" -f `
        $rank, `
        $q.Calls.ToString('N0'), `
        (Format-FriendlyTime $q.TotalMs), `
        (Format-FriendlyTime $q.MeanMs), `
        (Format-FriendlyTime $q.MaxMs), `
        $q.Rows.ToString('N0'), `
        "$($q.CacheHitPct)%", `
        $queryDisplay

    Write-Host "${colour}${line}${NC}"
}

# ============================================================================
# Fetch full query text for top queries
# ============================================================================

Write-Host ""
Write-Host "${BOLD}${CYAN}=== Full Query Text (Top $TopN) ===${NC}"
Write-Host ""

$fullTextSql = @"
SELECT
    queryid::text,
    regexp_replace(query, E'[\\n\\r\\t]+', ' ', 'g'),
    calls::text,
    ROUND(total_exec_time::numeric, 2)::text,
    ROUND(mean_exec_time::numeric, 2)::text
FROM pg_stat_statements
WHERE dbid = (SELECT oid FROM pg_database WHERE datname = 'jim')
ORDER BY total_exec_time DESC
LIMIT $TopN
"@

$fullTextResult = Invoke-PsqlDelimited -Sql $fullTextSql
$fullLines = ($fullTextResult -join "`n") -split "`n" | Where-Object { $_.Trim() -ne "" }

$fullQueries = @()
foreach ($line in $fullLines) {
    $fields = $line -split [regex]::Escape($DELIM)
    if ($fields.Count -ge 5) {
        $fullQueries += [PSCustomObject]@{
            QueryId = $fields[0].Trim()
            Query   = $fields[1].Trim()
            Calls   = $fields[2].Trim()
            TotalMs = $fields[3].Trim()
            MeanMs  = $fields[4].Trim()
        }
    }
}

$rank = 0
foreach ($fq in $fullQueries) {
    $rank++
    $formattedQuery = $fq.Query -replace '\s+', ' '
    Write-Host "${BOLD}#${rank}${NC} ${GRAY}(queryid: $($fq.QueryId), calls: $($fq.Calls), total: $($fq.TotalMs)ms, mean: $($fq.MeanMs)ms)${NC}"
    Write-Host "${formattedQuery}"
    Write-Host ""
}

# ============================================================================
# Save results to file
# ============================================================================

if (-not $OutputFile) {
    $hostname = (hostname).ToLower()
    $timestamp = Get-Date -Format "yyyy-MM-dd_HHmmss"
    $outputDir = Join-Path $scriptRoot "results" "query-analysis" $hostname
    if (-not (Test-Path $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }
    $OutputFile = Join-Path $outputDir "${Scenario}-${Template}-${DirectoryType}-${timestamp}.md"
}
else {
    $outputDir = Split-Path -Parent $OutputFile
    if (-not (Test-Path $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }
}

# Build markdown report
$md = @()
$md += "# Query Performance Analysis"
$md += ""
$md += "- **Date**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')"
$md += "- **Scenario**: $Scenario"
$md += "- **Template**: $Template"
$md += "- **Directory Type**: $DirectoryType"
$md += "- **Top N**: $TopN"
$md += "- **Total DB time (top $TopN)**: $(Format-FriendlyTime $totalTime)"
$md += "- **Total calls (top $TopN)**: $($totalCalls.ToString('N0'))"
$md += ""
$md += "## Top Queries by Total Execution Time"
$md += ""
$md += "| # | Calls | Total | Mean | Max | Rows | Cache% | Query |"
$md += "|---|-------|-------|------|-----|------|--------|-------|"

$rank = 0
foreach ($q in $queries) {
    $rank++
    $queryMd = ($q.QueryPreview -replace '\s+', ' ')
    if ($queryMd.Length -gt 120) {
        $queryMd = $queryMd.Substring(0, 117) + "..."
    }
    # Escape pipe characters for markdown
    $queryMd = $queryMd -replace '\|', '\\|'
    $md += "| $rank | $($q.Calls.ToString('N0')) | $(Format-FriendlyTime $q.TotalMs) | $(Format-FriendlyTime $q.MeanMs) | $(Format-FriendlyTime $q.MaxMs) | $($q.Rows.ToString('N0')) | $($q.CacheHitPct)% | ``$queryMd`` |"
}

$md += ""
$md += "## Full Query Text"
$md += ""

$rank = 0
foreach ($fq in $fullQueries) {
    $rank++
    $md += "### #$rank (queryid: $($fq.QueryId))"
    $md += ""
    $md += "- **Calls**: $($fq.Calls)"
    $md += "- **Total**: $($fq.TotalMs)ms"
    $md += "- **Mean**: $($fq.MeanMs)ms"
    $md += ""
    $md += '```sql'
    $md += $fq.Query
    $md += '```'
    $md += ""
}

$md -join "`n" | Set-Content -Path $OutputFile -Encoding utf8

Write-Host ""
Write-Host "${GREEN}Results saved to: ${NC}${OutputFile}"
Write-Host ""
