//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIM.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JIM.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adorable
        ///Adventurous
        ///Aggressive
        ///Agreeable
        ///Alert
        ///Alive
        ///Amused
        ///Angry
        ///Annoyed
        ///Annoying
        ///Anxious
        ///Arrogant
        ///Ashamed
        ///Attractive
        ///Average
        ///Awful
        ///Bad
        ///Beautiful
        ///Better
        ///Bewildered
        ///Black
        ///Bloody
        ///Blue
        ///Blue-Eyed
        ///Blushing
        ///Bored
        ///Brainy
        ///Brave
        ///Breakable
        ///Bright
        ///Busy
        ///Calm
        ///Careful
        ///Cautious
        ///Charming
        ///Cheerful
        ///Clean
        ///Clear
        ///Clever
        ///Cloudy
        ///Clumsy
        ///Colorful
        ///Combative
        ///Comfortable
        ///Concerned
        ///Condemned
        ///Confused
        ///Cooperative
        ///Courageous
        ///Crazy
        ///Creepy
        ///Crowded
        ///Cruel
        ///Curious
        ///Cute
        ///Dangerous
        ///Dark
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adjectives_en {
            get {
                return ResourceManager.GetString("Adjectives_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alizarin
        ///Amaranth
        ///Amber
        ///Amethyst
        ///Apricot
        ///Aqua
        ///Aquamarine
        ///Asparagus
        ///Auburn
        ///Azure
        ///Beige
        ///Bistre
        ///Black
        ///Blue
        ///Blue-Green
        ///Blue-Violet
        ///Bondi-Blue
        ///Brass
        ///Bronze
        ///Brown
        ///Buff
        ///Burgundy
        ///Camouflage-Green
        ///Caput-Mortuum
        ///Cardinal
        ///Carmine
        ///Carrot-Orange
        ///Celadon
        ///Cerise
        ///Cerulean
        ///Champagne
        ///Charcoal
        ///Chartreuse
        ///Cherry-Blossom-Pink
        ///Chestnut
        ///Chocolate
        ///Cinnabar
        ///Cinnamon
        ///Cobalt
        ///Copper
        ///Coral
        ///Corn
        ///Cornflower
        ///Cream
        ///Crimson
        ///Cyan
        ///Dandelion
        ///Denim
        ///Ecru
        ///Emerald
        ///Eggplant
        ///Falu-Red
        ///Fern-Green
        ///Fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Colours_en {
            get {
                return ResourceManager.GetString("Colours_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOAM
        ///Acme Corp
        ///Sirius Cybernetics Corp
        ///MomCorp
        ///Rich Industries
        ///Soylent Corp
        ///Very Big Corp. of America
        ///Frobozz Magic Co
        ///Warbucks Industries
        ///Tyrell Corp
        ///Wayne Enterprises
        ///Virtucon
        ///Globex
        ///Umbrella Corp
        ///Wonka Industries
        ///Stark Industries
        ///Clampett Oil
        ///Oceanic Airlines
        ///Yoyodyne Propulsion Sys
        ///Cyberdyne Systems Corp
        ///d&apos;Anconia Copper
        ///Gringotts
        ///Oscorp
        ///Nakatomi Trading Corp
        ///Spacely Space Sprockets.
        /// </summary>
        internal static string Companies_en {
            get {
                return ResourceManager.GetString("Companies_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing
        ///Operations
        ///Finance
        ///Sales
        ///Human Resources
        ///Procurement
        ///Information Technology
        ///Research &amp; Development
        ///Executive
        ///Legal
        ///Facilities
        ///Catering.
        /// </summary>
        internal static string Departments_en {
            get {
                return ResourceManager.GetString("Departments_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abigail
        ///Ada
        ///Aisha
        ///Alice
        ///Amber
        ///Amelia
        ///Amelie
        ///Anna
        ///Arabella
        ///Aria
        ///Aurora
        ///Ava
        ///Ayla
        ///Bella
        ///Bonnie
        ///Charlotte
        ///Chloe
        ///Clara
        ///Daisy
        ///Darcie
        ///Delilah
        ///Eden
        ///Edith
        ///Eleanor
        ///Eliza
        ///Elizabeth
        ///Ella
        ///Ellie
        ///Elodie
        ///Elsie
        ///Emilia
        ///Emily
        ///Emma
        ///Erin
        ///Esme
        ///Eva
        ///Evelyn
        ///Evie
        ///Florence
        ///Freya
        ///Georgia
        ///Grace
        ///Gracie
        ///Hallie
        ///Hannah
        ///Harper
        ///Harriet
        ///Heidi
        ///Holly
        ///Imogen
        ///Iris
        ///Isabella
        ///Isabelle
        ///Isla
        ///Ivy
        ///Jasmine
        ///Jessica
        ///Layla
        ///Lilly
        ///Lily
        ///Lola
        ///Lottie
        ///Lucy
        ///Luna
        ///Lyla
        ///Lyra
        ///Mabel
        ///Maeve
        ///Maisie
        ///Margot
        ///Maria
        ///Maryam
        ///Matilda
        ///Maya
        ///Mia
        ///Mila
        ///Millie
        ///Molly
        ///Myla
        ///Nancy
        ///Olive
        ///Ol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstnamesFemale_en {
            get {
                return ResourceManager.GetString("FirstnamesFemale_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adam
        ///Albert
        ///Albie
        ///Alexander
        ///Alfie
        ///Alfred
        ///Archie
        ///Arlo
        ///Arthur
        ///Benjamin
        ///Bobby
        ///Caleb
        ///Carter
        ///Charles
        ///Charlie
        ///Chester
        ///Daniel
        ///David
        ///Dylan
        ///Edward
        ///Elijah
        ///Elliot
        ///Elliott
        ///Ellis
        ///Ethan
        ///Ezra
        ///Felix
        ///Finley
        ///Finn
        ///Frankie
        ///Freddie
        ///Frederick
        ///Gabriel
        ///George
        ///Grayson
        ///Harley
        ///Harrison
        ///Harry
        ///Harvey
        ///Henry
        ///Hudson
        ///Hugo
        ///Hunter
        ///Ibrahim
        ///Isaac
        ///Jack
        ///Jackson
        ///Jacob
        ///James
        ///Jasper
        ///Jaxon
        ///Jayden
        ///Jenson
        ///Jesse
        ///Joseph
        ///Joshua
        ///Jude
        ///Leo
        ///Leon
        ///Liam
        ///Logan
        ///Louie
        ///Louis
        ///Luca
        ///Lucas
        ///Mason
        ///Max
        ///Michael
        ///Milo
        ///Mohammad
        ///Mohammed
        ///Muhammad
        ///Myles
        ///Noah
        ///Oakley
        ///Oliver
        ///Ollie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstnamesMale_en {
            get {
                return ResourceManager.GetString("FirstnamesMale_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company
        ///Division
        ///Department
        ///Team
        ///Project
        ///Programme
        ///Subjects
        ///Compliance
        ///Approvers
        ///Reviewers
        ///Advisors
        ///Consultants
        ///Management
        ///Licensing.
        /// </summary>
        internal static string GroupNameEndings_en {
            get {
                return ResourceManager.GetString("GroupNameEndings_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Specialist
        ///Marketing Manager
        ///Marketing Director
        ///Graphic Designer
        ///Marketing Research Analyst
        ///Marketing Communications Manager
        ///Marketing Consultant
        ///Product Manager
        ///Public Relations
        ///Social Media Assistant
        ///Brand Manager
        ///SEO Manager
        ///Content Marketing Manager
        ///Copywriter
        ///Media Buyer
        ///Digital Marketing Manager
        ///eCommerce Marketing Specialist
        ///Brand Strategist
        ///Vice President of Marketing
        ///Media Relations Coordinator
        ///Administrative Assistant
        ///Receptionist
        ///Office Manager
        ///Auditing Clerk
        ///Boo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobTitles_en {
            get {
                return ResourceManager.GetString("JobTitles_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Jones
        ///Brown
        ///Taylor
        ///Wilson
        ///Davies
        ///Evans
        ///Johnson
        ///Thomas
        ///Roberts
        ///Walker
        ///Wright
        ///Thompson
        ///Robinson
        ///White
        ///Hall
        ///Hughes
        ///Green
        ///Edwards
        ///Martin
        ///Wood
        ///Clarke
        ///Harris
        ///Jackson
        ///Lewis
        ///Clark
        ///Turner
        ///Scott
        ///Hill
        ///Moore
        ///Williams
        ///Cooper
        ///Ward
        ///Morris
        ///King
        ///Watson
        ///Harrison
        ///Baker
        ///Young
        ///Allen
        ///Morgan
        ///Anderson
        ///Mitchell
        ///Phillips
        ///James
        ///Bell
        ///Campbell
        ///Lee
        ///Kelly
        ///Davis
        ///Parker
        ///Bennett
        ///Miller
        ///Shaw
        ///Cook
        ///Simpson
        ///Richardson
        ///Price
        ///Marshall
        ///Collins
        ///Carter
        ///Stewart
        ///Bailey
        ///Griffiths
        ///Gra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lastnames_en {
            get {
                return ResourceManager.GetString("Lastnames_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Water Coolers
        ///The Scanners
        ///Boss Mode
        ///Lunch Room Bandits
        ///Never Overtime
        ///We Break for No-one
        ///Desk Champions
        ///Office Heroes
        ///Not Your Ordinary Desk Jockeys
        ///Better Nine Than Five
        ///All Play and No Work
        ///Whiz Holics
        ///Logistic Zealots
        ///Mind Mantra
        ///Smash Audit
        ///Market Moghuls
        ///Greed Breed
        ///Brain Acumen
        ///Mind Messiahs
        ///Buzz Logic
        ///Spartan Policies
        ///Dream Crushers
        ///The Credit Crunchers
        ///The Rockin Edits
        ///The Mind Bogglers
        ///Member Support
        ///Business Ties
        ///Labor Force of Nature
        ///Legal Eagles
        ///Cubicle Comics        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teams_en {
            get {
                return ResourceManager.GetString("Teams_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atm
        ///Cd
        ///Suv
        ///Tv
        ///Aardvark
        ///Abacus
        ///Abbey
        ///Abbreviation
        ///Abdomen
        ///Ability
        ///Abnormality
        ///Abolishment
        ///Abortion
        ///Abrogation
        ///Absence
        ///Abundance
        ///Abuse
        ///Academics
        ///Academy
        ///Accelerant
        ///Accelerator
        ///Accent
        ///Acceptance
        ///Access
        ///Accessory
        ///Accident
        ///Accommodation
        ///Accompanist
        ///Accomplishment
        ///Accord
        ///Accordance
        ///Accordion
        ///Account
        ///Accountability
        ///Accountant
        ///Accounting
        ///Accuracy
        ///Accusation
        ///Acetate
        ///Achievement
        ///Achiever
        ///Acid
        ///Acknowledgment
        ///Acorn
        ///Acoustics
        ///Acquaintance
        ///Acquisition
        ///Acre
        ///Acrylic
        ///Act
        ///Act [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Words_en {
            get {
                return ResourceManager.GetString("Words_en", resourceCulture);
            }
        }
    }
}
