// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

using System.ComponentModel.DataAnnotations;
using JIM.Models.Staging;

namespace JIM.Web.Models.Api;

/// <summary>
/// Asks JIM to set the password on one Connected System Object (issue #1121).
/// <para>
/// The password is supplied by the caller rather than generated by JIM. Generation is a portal affordance,
/// where the value is shown once to the administrator who asked for it and is never persisted; an API that
/// generated one would have to return it in a response body, and password values do not go in those.
/// </para>
/// </summary>
public class SetConnectedSystemObjectPasswordRequest
{
    /// <summary>
    /// The password to set. Sent to the Connected System and nowhere else: never logged, never persisted, and
    /// never echoed back in the response.
    /// </summary>
    [Required]
    public string Password { get; set; } = string.Empty;

    /// <summary>
    /// What should happen to the password once it is set. Omitted defaults to requiring a change at the next
    /// sign-in, which is the right default for a password somebody else chose. A Connected System that cannot
    /// honour the request applies what it can and says so in the response.
    /// </summary>
    public PasswordExpiryBehaviour? ExpiryBehaviour { get; set; }

    /// <summary>
    /// Whether to enable the account as part of setting the password. Omitted leaves the account's enabled state
    /// untouched, which is the right choice for a reset on an account that is already how the administrator
    /// wants it. True is for an account that was created disabled awaiting a compliant password.
    /// </summary>
    public bool? EnableAccount { get; set; }
}

/// <summary>
/// What happened when the password was set. <b>Carries no password value</b>, by design.
/// </summary>
public class SetConnectedSystemObjectPasswordResponse
{
    /// <summary>
    /// The expiry behaviour actually applied to the account, which is not always the one requested: a directory
    /// with no equivalent of what was asked for applies what it can. This reports what the account really has.
    /// </summary>
    public PasswordExpiryBehaviour AppliedExpiryBehaviour { get; set; }

    /// <summary>
    /// Set when the requested expiry behaviour could not be honoured, naming what was asked for and what
    /// happened instead. Null when the request was applied as asked.
    /// </summary>
    public string? ExpiryBehaviourWarning { get; set; }

    /// <summary>
    /// Builds the response from a successful password set.
    /// </summary>
    public static SetConnectedSystemObjectPasswordResponse FromResult(PasswordSetResult result, PasswordExpiryBehaviour requested) =>
        new()
        {
            AppliedExpiryBehaviour = result.AppliedExpiryBehaviour ?? requested,
            ExpiryBehaviourWarning = result.ExpiryBehaviourWarning
        };
}
