// Copyright (c) Tetron Limited. All rights reserved.
// Licensed under the Tetron Commercial License. See LICENSE file in the project root.

using System.ComponentModel.DataAnnotations;
using JIM.Models.Staging;

namespace JIM.Web.Models.Api;

/// <summary>
/// Asks JIM to set the password on one Connected System Object (#1121, #1635): the account-scoped form of Set
/// Password, which queues the change for that one account and waits briefly for the outcome. The response is the
/// same per-target shape the Metaverse Object operation returns, <see cref="SetMetaverseObjectPasswordResponse"/>.
/// <para>
/// The password is supplied by the caller rather than generated by JIM. Generation is a portal affordance, where
/// the value is shown once to the administrator who asked for it and is never persisted; an API that generated one
/// would have to return it in a response body, and password values do not go in those.
/// </para>
/// </summary>
public class SetConnectedSystemObjectPasswordRequest
{
    /// <summary>
    /// The password to set. Encrypted before it is stored, held only until it is delivered, never logged, never
    /// returned, and never recorded on an Activity.
    /// </summary>
    [Required]
    public string Password { get; set; } = string.Empty;

    /// <summary>
    /// What should happen to the password once it is set. Omitted defaults to requiring a change at the next
    /// sign-in, which is the right default for a password somebody else chose. A Connected System that cannot
    /// honour the request applies what it can and says so in the outcome's message.
    /// </summary>
    public PasswordExpiryBehaviour? ExpiryBehaviour { get; set; }

    /// <summary>
    /// Whether to enable the account as part of setting the password. Omitted leaves the account's enabled state
    /// untouched, which is the right choice for a reset on an account that is already how the administrator
    /// wants it. True is for an account that was created disabled awaiting a compliant password.
    /// </summary>
    public bool? EnableAccount { get; set; }

    /// <summary>
    /// How many seconds to wait for delivery before answering, 0 to 30. Omitted waits
    /// <see cref="SetMetaverseObjectPasswordRequest.DefaultWaitSecondsForNamedAccounts"/> seconds, long enough for
    /// the Password Delivery Service to have written the password and for the account to report what it did with
    /// it. Pass 0 to return as soon as the change is recorded. With a wait, the response is <c>200</c> once the
    /// account has settled (set, retrying, parked) or <c>202</c> with what is known when the time runs out;
    /// delivery continues either way.
    /// </summary>
    [Range(SetMetaverseObjectPasswordRequest.MinimumWaitSeconds, SetMetaverseObjectPasswordRequest.MaximumWaitSeconds)]
    public int? Wait { get; set; }
}
